<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />

  <ItemGroup>
    <PackageReference Include="SignalRSwaggerGen" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Authority\Monica.Authority.csproj" />
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
  </ItemGroup>
</Project>
