<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateStaticWebAssetsManifest>true</GenerateStaticWebAssetsManifest>
    <PackageDescription>SignalR integration for Monica framework with Swagger documentation support, enabling real-time bidirectional communication between server and clients.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SignalRSwaggerGen" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Authority\Monica.Authority.csproj" />
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.UI\Monica.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\**\*.json" />
  </ItemGroup>
</Project>
