<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml"/>


  <ItemGroup>
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="ExpressionDebugger" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Tool\MoLibrary.Tool.csproj" />
  </ItemGroup>


</Project>
