<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />


  <ItemGroup>
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Mapster" Version="7.4.0" />
	  <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="ExpressionDebugger" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Tool\MoLibrary.Tool.csproj" />
  </ItemGroup>


</Project>
