<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.xml"></Import>


  <ItemGroup>
    <ProjectReference Include="..\..\MoLibrary.DataChannel\MoLibrary.DataChannel.csproj" />
    <ProjectReference Include="..\..\MoLibrary.Framework\MoLibrary.Framework.csproj" />
  </ItemGroup>

</Project>