<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageDescription>Repository pattern implementation with Entity Framework Core integration for Monica framework, providing data access abstractions and CRUD operations.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Authority\Monica.Authority.csproj" />
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.DependencyInjection\Monica.DependencyInjection.csproj" />
    <ProjectReference Include="..\Monica.EventBus\Monica.EventBus.csproj" />
  </ItemGroup>
</Project>
