// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monica.Configuration.EfCore.DbContext;

#nullable disable

namespace Test.Monica.Configuration.EfCore.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20260717113851_InitialConfigurationStoreTestSchema")]
    partial class InitialConfigurationStoreTestSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationDefinitionEntity", b =>
                {
                    b.Property<string>("DefinitionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ClrTypeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DefinitionIdentity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<int>("DefinitionRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("FromProject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ReloadBehavior")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SchemaHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("DefinitionKey");

                    b.HasIndex("Category");

                    b.HasIndex("DefinitionIdentity")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigDef_Identity");

                    b.HasIndex("FromProject");

                    b.ToTable("ConfigurationDefinitions");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationDefinitionPublishHistoryEntity", b =>
                {
                    b.Property<string>("HistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ChangeSummaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DefinitionIdentity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("DefinitionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("FromProject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("NewSchemaHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("NewSchemaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("NewSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousSchemaHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PreviousSchemaJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("PreviousSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PublisherVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("HistoryId");

                    b.HasIndex("DefinitionIdentity", "DefinitionRevision")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigDefPub_Identity_Revision");

                    b.ToTable("ConfigurationDefinitionPublishHistories");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationDefinitionPublisherStateEntity", b =>
                {
                    b.Property<string>("DefinitionIdentity")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("PublisherIdentity")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("ObservationKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PublisherKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(191)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ReloadBehavior")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("DefinitionIdentity", "PublisherIdentity");

                    b.HasIndex("PublisherIdentity")
                        .HasDatabaseName("IX_ConfigDefPublisher_Publisher");

                    b.ToTable("ConfigurationDefinitionPublisherStates", (string)null);
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationEffectiveValueEntity", b =>
                {
                    b.Property<string>("DefinitionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdentity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("Json")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<string>("LastModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("LastModifierName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("DefinitionKey");

                    b.HasIndex("DefinitionIdentity")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigValue_Identity");

                    b.ToTable("ConfigurationEffectiveValues");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationMutationGroupEntity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<string>("DefinitionKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Label")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ModifierName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("MutationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("RolledBackGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("RolledBackTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("GroupId");

                    b.HasIndex("CreatedTime");

                    b.ToTable("ConfigurationMutationGroups");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationStoreLockEntity", b =>
                {
                    b.Property<string>("LockKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("LockVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("LockKey");

                    b.ToTable("ConfigurationStoreLocks", (string)null);

                    b.HasData(
                        new
                        {
                            LockKey = "DefinitionPublication",
                            LockVersion = 0L
                        },
                        new
                        {
                            LockKey = "MutationGroups",
                            LockVersion = 0L
                        },
                        new
                        {
                            LockKey = "UnifiedVersions",
                            LockVersion = 0L
                        });
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationUnifiedVersionDocumentEntity", b =>
                {
                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DefinitionIdentity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<long?>("EffectiveValueVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromProject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Json")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SchemaHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContributionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Version", "DefinitionKey");

                    b.HasIndex("DefinitionIdentity", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigVerDoc_Identity_Version");

                    b.ToTable("ConfigurationUnifiedVersionDocuments");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationUnifiedVersionEntity", b =>
                {
                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<int>("DefinitionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ModifierName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("MutationGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("TriggerDefinitionKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Version");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("MutationGroupId");

                    b.ToTable("ConfigurationUnifiedVersions");
                });

            modelBuilder.Entity("Monica.Configuration.EfCore.Entities.ConfigurationValueHistoryEntity", b =>
                {
                    b.Property<string>("HistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DefinitionIdentity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("ModifiedTime")
                        .HasPrecision(6)
                        .HasColumnType("timestamp");

                    b.Property<string>("ModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ModifierName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("MutationGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("MutationKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("NewValueJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("OldValueJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("PathDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SchemaHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceConfigurationPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourceDisplayName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourcePhysicalPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourceProviderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourceRevisionAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourceRevisionBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoryId");

                    b.HasIndex("MutationGroupId");

                    b.HasIndex("DefinitionIdentity", "PathDepth", "ModifiedTime")
                        .HasDatabaseName("IX_ConfigHist_Identity_Depth_Time");

                    b.ToTable("ConfigurationValueHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
