<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.xml"/>


	<ItemGroup>
		<PackageReference Include="Cronos" Version="0.11.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoLibrary.Core\MoLibrary.Core.csproj" />
		<ProjectReference Include="..\MoLibrary.DependencyInjection\MoLibrary.DependencyInjection.csproj" />
		<ProjectReference Include="..\MoLibrary.EventBus\MoLibrary.EventBus.csproj" />
		<ProjectReference Include="..\MoLibrary.RegisterCentre\MoLibrary.RegisterCentre.csproj" />
		<ProjectReference Include="..\MoLibrary.StateStore\MoLibrary.StateStore.csproj" />
	</ItemGroup>
</Project>
