<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml"/>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Authority\MoLibrary.Authority.csproj" />
    <ProjectReference Include="..\MoLibrary.Core\MoLibrary.Core.csproj" />
    <ProjectReference Include="..\MoLibrary.EventBus\MoLibrary.EventBus.csproj" />
  </ItemGroup>
</Project>
