<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />

  <ItemGroup>
    <PackageReference Include="DotNetCore.EntityFrameworkCore.GaussDB" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Authority\MoLibrary.Authority.csproj" />
    <ProjectReference Include="..\MoLibrary.Core\MoLibrary.Core.csproj" />
    <ProjectReference Include="..\MoLibrary.EventBus\MoLibrary.EventBus.csproj" />
  </ItemGroup>
</Project>
