<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.xml"/>


    <ItemGroup>
        <ProjectReference Include="..\MoLibrary.JobScheduler\MoLibrary.JobScheduler.csproj" />
        <ProjectReference Include="..\MoLibrary.Repository\MoLibrary.Repository.csproj" />
    </ItemGroup>

</Project>
