<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageDescription>Fundamental types, utilities, and base infrastructure for Monica framework including built-in mediator dispatch, Mapster mapping, and core abstractions.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
	<PackageReference Include="Microsoft.Extensions.Resilience" Version="10.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8">
      <ExcludeAssets>analyzers</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.8" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="ExpressionDebugger" Version="2.2.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monica.Tool\Monica.Tool.csproj" />
  </ItemGroup>


</Project>
