<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />

  <PropertyGroup>
    <PackageDescription>State management and persistence abstractions for Monica framework, providing unified interfaces for distributed state storage.</PackageDescription>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
  </ItemGroup>
</Project>
