<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateStaticWebAssetsManifest>true</GenerateStaticWebAssetsManifest>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1998</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.JobScheduler\MoLibrary.JobScheduler.csproj" />
    <ProjectReference Include="..\MoLibrary.UI\MoLibrary.UI.csproj" />
  </ItemGroup>
</Project>
