<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />


  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.StateStore\Monica.StateStore.csproj" />
    <ProjectReference Include="..\Monica.RegisterCentre\Monica.RegisterCentre.csproj" />
  </ItemGroup>

</Project>
