window.SYSTEM_INFO_DATA = {
  service: {
    name: "Flight Service",
    nameZh: "航班服务",
    code: "DEV-SERVICE-FLIGHT-API",
    monogram: "M",
    environment: "Development",
    environmentZh: "开发环境",
    version: "v1.0.3",
    uptime: "01:46:22",
    startupMs: 3189.0308,
    readyAt: "2026-08-07 09:42:18.417 +08:00",
    processStartedAt: "2026-08-07 09:42:15.122 +08:00"
  },
  pulse: {
    workingSet: "286.4 MB",
    processId: "24,816",
    capturedAt: "10:28:40",
    captureAgeSeconds: 0
  },
  runtime: [
    { icon: "box", key: "dotnet", value: ".NET 10.0.0-preview.6", tone: "violet" },
    { icon: "cpu", key: "processArchitecture", value: "64-bit process", valueZh: "64 位进程", tone: "cyan" },
    { icon: "shield-check", key: "privilege", value: "Not privileged", valueZh: "非特权进程", tone: "slate" },
    { icon: "layers-3", key: "pageSize", value: "4,096 bytes", valueZh: "4,096 字节", tone: "slate" },
    { icon: "mouse-pointer-2", key: "interactive", value: "No", valueZh: "否", tone: "slate" }
  ],
  environment: [
    { icon: "server", key: "machine", value: "DEV-FLIGHT-NODE-03", tone: "violet" },
    { icon: "user-round", key: "user", value: "svc_flight_api", tone: "cyan" },
    { icon: "monitor", key: "os", value: "Microsoft Windows 11 10.0.26100", tone: "slate" },
    { icon: "clock-3", key: "timezone", value: "China Standard Time · UTC+08:00", valueZh: "中国标准时间 · UTC+08:00", tone: "slate" },
    { icon: "folder-open", key: "directory", value: "D:\\Code\\FIPS2022\\src\\Services\\FlightService\\FlightService.API", tone: "slate", long: true },
    { icon: "file-cog", key: "processPath", value: "D:\\Code\\FIPS2022\\artifacts\\bin\\FlightService.API\\debug\\FlightService.API.exe", tone: "slate", long: true }
  ],
  endpoints: [
    {
      scheme: "HTTPS",
      address: "https://localhost:7093"
    },
    {
      scheme: "HTTP",
      address: "http://localhost:5093"
    }
  ],
  build: {
    productName: "FIPS2022 Flight Service",
    productVersion: "1.0.3+f1a98c76f3",
    fileVersion: "1.0.3.0",
    builtAt: "2026-08-07 09:37:54 +08:00",
    company: "Monica",
    copyright: "Copyright © Monica 2026"
  },
  customLinks: [
    { icon: "braces", key: "api", href: "#", accent: "violet", category: "Monica", target: "newTab" },
    { icon: "blocks", key: "modules", href: "#", accent: "cyan", category: "Monica", target: "sameTab" },
    {
      icon: "chart-no-axes-combined",
      key: "observability",
      href: "#",
      accent: "emerald",
      category: "Operations",
      categoryZh: "运维",
      target: "newTab",
      credentials: { userName: "observer", password: "••••••••••••" }
    }
  ],
  restart: {
    enabled: true,
    delaySeconds: 3
  },
  i18n: {
    en: {
      shellName: "Flight Service",
      prototype: "SYSTEM DOSSIER / PROTOTYPE",
      controlsAria: "Prototype controls",
      startupAria: "Application startup timing",
      pulseAria: "Service evidence summary",
      indexAria: "Dossier index",
      pageEyebrow: "MONICA / LIVE SERVICE PROFILE",
      pageTitle: "System dossier",
      pageSummary: "Identity, readiness and runtime evidence for this host instance.",
      development: "Development",
      ready: "Ready",
      uptime: "Process uptime",
      processStart: "Process started",
      tracked: "Tracked",
      startupTitle: "Application startup",
      startupScope: "Start marker → ready",
      startupReadyAt: "Host ready at",
      startMarker: "Start marker",
      hostReady: "Host ready",
      duration: "3,189.0308 ms",
      trackedToggle: "Startup tracked",
      untrackedToggle: "Startup untracked",
      untrackedNote: "Startup timing is intentionally absent in this state.",
      refresh: "Refresh evidence",
      restart: "Restart service",
      theme: "Switch theme",
      language: "Switch language",
      density: "Toggle density",
      uptimeMetric: "Process uptime",
      memoryMetric: "Working set",
      pidMetric: "Process ID",
      captureMetric: "Evidence age",
      running: "RUNNING",
      snapshot: "SNAPSHOT",
      processIdCode: "PID",
      justNow: "just now",
      secondsAgo: "{0}s ago",
      dossierIndex: "Dossier index",
      indexHint: "Jump to evidence",
      runtime: "Runtime pulse",
      runtimeNote: "Process and managed runtime",
      environment: "Environment fingerprint",
      environmentNote: "Host identity and execution context",
      endpoints: "Listening endpoints",
      endpointsNote: "Addresses currently bound by the host",
      build: "Artifact evidence",
      buildNote: "Product and artifact metadata",
      routes: "Configured links",
      routesNote: "Host-provided operational destinations",
      dotnet: ".NET runtime",
      processArchitecture: "Process architecture",
      privilege: "Privilege",
      pageSize: "System page size",
      interactive: "User interactive",
      machine: "Machine",
      user: "Process user",
      os: "Operating system",
      timezone: "Time zone",
      directory: "Working directory",
      processPath: "Process path",
      memorySnapshot: "exact process working set at capture",
      evidence: "evidence",
      listening: "addresses",
      bound: "Bound",
      inspect: "Inspect",
      open: "Open",
      address: "Listening address",
      product: "Product",
      productVersion: "Product version",
      fileVersion: "File version",
      builtAt: "Artifact timestamp",
      company: "Company",
      legal: "Legal",
      apiTitle: "API management",
      apiDescription: "Inspect and exercise HTTP endpoints.",
      modulesTitle: "Module workbench",
      modulesDescription: "Trace composition, dependencies and discovery.",
      logsTitle: "Runtime logs",
      logsDescription: "Continue into structured application evidence.",
      observabilityTitle: "Observability console",
      observabilityDescription: "Open the configured metrics and trace surface.",
      newTab: "New tab",
      sameTab: "Same tab",
      access: "Access",
      userName: "User name",
      password: "Password",
      copyUserName: "Copy user name",
      copyPassword: "Copy password",
      copied: "Credential copied",
      gracefulShutdown: "GRACEFUL SHUTDOWN",
      restartTitle: "Request graceful shutdown?",
      restartBody: "A graceful shutdown request will be scheduled after the configured delay. An external supervisor controls whether this service starts again.",
      restartDelay: "Shutdown will begin about {0} seconds after confirmation.",
      restartFact: "This is not an in-process restart.",
      cancel: "Cancel",
      confirmRestart: "Request shutdown",
      restartRequested: "Shutdown requested",
      refreshed: "System evidence refreshed",
      endpointTitle: "Endpoint evidence",
      close: "Close",
      captured: "Captured",
      transport: "Transport",
      exactAddress: "Exact address",
      compact: "Compact",
      comfortable: "Comfortable"
    },
    zh: {
      shellName: "航班服务",
      prototype: "系统档案 / 交互原型",
      controlsAria: "原型控制项",
      startupAria: "应用启动计时",
      pulseAria: "服务证据摘要",
      indexAria: "档案索引",
      pageEyebrow: "MONICA / 实时服务档案",
      pageTitle: "系统档案",
      pageSummary: "集中查看当前宿主实例的身份、就绪状态与运行证据。",
      development: "开发环境",
      ready: "已就绪",
      uptime: "进程运行时长",
      processStart: "进程启动于",
      tracked: "已记录",
      startupTitle: "应用启动",
      startupScope: "计时起点 → 就绪",
      startupReadyAt: "宿主就绪于",
      startMarker: "计时起点",
      hostReady: "宿主就绪",
      duration: "3,189.0308 ms",
      trackedToggle: "已跟踪启动",
      untrackedToggle: "未跟踪启动",
      untrackedNote: "当前状态按契约完全隐藏启动计时。",
      refresh: "刷新证据",
      restart: "重启服务",
      theme: "切换主题",
      language: "切换语言",
      density: "切换密度",
      uptimeMetric: "进程运行时长",
      memoryMetric: "工作集",
      pidMetric: "进程 ID",
      captureMetric: "证据时效",
      running: "运行中",
      snapshot: "快照",
      processIdCode: "进程",
      justNow: "刚刚",
      secondsAgo: "{0} 秒前",
      dossierIndex: "档案索引",
      indexHint: "快速定位证据",
      runtime: "运行脉搏",
      runtimeNote: "进程与托管运行时",
      environment: "环境指纹",
      environmentNote: "宿主身份与执行上下文",
      endpoints: "监听端点",
      endpointsNote: "当前宿主已绑定的地址",
      build: "制品证据",
      buildNote: "产品与制品元数据",
      routes: "配置链接",
      routesNote: "由宿主配置的运维目的地",
      dotnet: ".NET 运行时",
      processArchitecture: "进程架构",
      privilege: "权限级别",
      pageSize: "系统页面大小",
      interactive: "用户交互式",
      machine: "机器",
      user: "进程用户",
      os: "操作系统",
      timezone: "时区",
      directory: "工作目录",
      processPath: "进程路径",
      memorySnapshot: "采集时的精确进程工作集",
      evidence: "项证据",
      listening: "个地址",
      bound: "已绑定",
      inspect: "查看",
      open: "打开",
      address: "监听地址",
      product: "产品",
      productVersion: "产品版本",
      fileVersion: "文件版本",
      builtAt: "制品时间戳",
      company: "公司",
      legal: "版权",
      apiTitle: "接口管理",
      apiDescription: "查看并调试 HTTP 接口。",
      modulesTitle: "模块工作台",
      modulesDescription: "追踪组合、依赖和类型发现。",
      logsTitle: "运行日志",
      logsDescription: "继续查看结构化应用证据。",
      observabilityTitle: "可观测控制台",
      observabilityDescription: "打开已配置的指标与追踪界面。",
      newTab: "新标签页",
      sameTab: "当前页",
      access: "访问凭据",
      userName: "用户名",
      password: "密码",
      copyUserName: "复制用户名",
      copyPassword: "复制密码",
      copied: "凭据已复制",
      gracefulShutdown: "优雅关闭",
      restartTitle: "请求优雅关闭？",
      restartBody: "系统会在配置的延迟后请求宿主优雅关闭。服务是否再次启动由外部托管器决定。",
      restartDelay: "确认后大约 {0} 秒开始关闭。",
      restartFact: "这不是进程内自重启。",
      cancel: "取消",
      confirmRestart: "请求关闭",
      restartRequested: "已请求关闭",
      refreshed: "系统证据已刷新",
      endpointTitle: "端点证据",
      close: "关闭",
      captured: "采集时间",
      transport: "传输",
      exactAddress: "完整地址",
      compact: "紧凑",
      comfortable: "舒适"
    }
  }
};
