using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text.Encodings.Web;
using System.Text.Json;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace Monica.Generators.AutoController.BuildTasks;

/// <summary>
/// Exports RPC metadata generated by <c>HttpApiControllerSourceGenerator</c> into a deterministic JSON file.
/// </summary>
public sealed class ExportRpcMetadataTask : Microsoft.Build.Utilities.Task
{
    private const string METADATA_TYPE_NAMESPACE = "RpcMetadataGeneration";
    private const string METADATA_TYPE_NAME = "__RpcMetadataMarker";
    private const string METADATA_FIELD_NAME = "MetadataJson";

    /// <summary>
    /// Gets or sets the absolute directory of the project being built.
    /// Relative input and output paths are resolved against this directory.
    /// </summary>
    [Required]
    public string ProjectDirectory { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the path of the assembly produced by the current compilation.
    /// The task reads the compiled metadata marker from this assembly without loading or executing it.
    /// </summary>
    [Required]
    public string CompiledAssemblyPath { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the assembly name expected in both the compiled assembly and its RPC metadata document.
    /// A mismatch fails the export instead of allowing metadata from another producer to be selected.
    /// </summary>
    [Required]
    public string ExpectedAssemblyName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the directory where the deterministic RPC metadata document is written.
    /// A relative path is resolved against <see cref="ProjectDirectory"/>.
    /// </summary>
    [Required]
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>
    /// Gets the full path of the exported RPC metadata file after a successful execution.
    /// </summary>
    [Output]
    public string? OutputFilePath { get; private set; }

    public override bool Execute()
    {
        try
        {
            var projectDirectory = ResolvePath(ProjectDirectory);
            var compiledAssemblyPath = ResolvePath(projectDirectory, CompiledAssemblyPath);
            var outputDirectory = ResolvePath(projectDirectory, OutputDirectory);

            if (!File.Exists(compiledAssemblyPath))
            {
                Log.LogError(
                    "RPC metadata export failed for '{0}'. Compiled assembly '{1}' does not exist.",
                    ExpectedAssemblyName,
                    compiledAssemblyPath);
                return false;
            }

            var document = ReadMetadataDocument(compiledAssemblyPath, ExpectedAssemblyName);
            Directory.CreateDirectory(outputDirectory);

            var outputFilePath = Path.Combine(outputDirectory, $"{ExpectedAssemblyName}.rpc-metadata.json");
            var serializedContent = SerializeMetadata(document);

            if (File.Exists(outputFilePath))
            {
                var currentContent = File.ReadAllText(outputFilePath);
                if (string.Equals(NormalizeLineEndings(currentContent), serializedContent, StringComparison.Ordinal))
                {
                    OutputFilePath = outputFilePath;
                    Log.LogMessage(
                        MessageImportance.Low,
                        "RPC metadata is already up to date: {0}",
                        outputFilePath);
                    return true;
                }
            }

            WriteAtomically(outputFilePath, serializedContent);
            OutputFilePath = outputFilePath;

            Log.LogMessage(
                MessageImportance.High,
                "Exported RPC metadata for '{0}' to '{1}'.",
                ExpectedAssemblyName,
                outputFilePath);
            return true;
        }
        catch (Exception ex)
        {
            Log.LogErrorFromException(ex, showStackTrace: true);
            return false;
        }
    }

    private static RpcMetadataDocument ReadMetadataDocument(
        string compiledAssemblyPath,
        string expectedAssemblyName)
    {
        if (string.IsNullOrWhiteSpace(expectedAssemblyName))
        {
            throw new InvalidOperationException("The expected assembly name is required for RPC metadata export.");
        }

        using var assemblyStream = new FileStream(
            compiledAssemblyPath,
            FileMode.Open,
            FileAccess.Read,
            FileShare.ReadWrite | FileShare.Delete);
        using var peReader = new PEReader(assemblyStream);

        if (!peReader.HasMetadata)
        {
            throw new InvalidDataException($"Compiled assembly '{compiledAssemblyPath}' does not contain managed metadata.");
        }

        var metadataReader = peReader.GetMetadataReader();
        if (!metadataReader.IsAssembly)
        {
            throw new InvalidDataException($"Compiled output '{compiledAssemblyPath}' is not an assembly.");
        }

        var compiledAssemblyName = metadataReader.GetString(metadataReader.GetAssemblyDefinition().Name);
        if (!string.Equals(compiledAssemblyName, expectedAssemblyName, StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                $"RPC metadata export expected assembly '{expectedAssemblyName}', but compiled output '{compiledAssemblyPath}' is '{compiledAssemblyName}'.");
        }

        var markerTypes = metadataReader.TypeDefinitions
            .Where(handle => IsMetadataMarker(metadataReader, handle))
            .ToList();
        if (markerTypes.Count != 1)
        {
            throw new InvalidDataException(
                $"Assembly '{expectedAssemblyName}' must contain exactly one '{METADATA_TYPE_NAMESPACE}.{METADATA_TYPE_NAME}' type, but {markerTypes.Count} were found.");
        }

        var markerType = metadataReader.GetTypeDefinition(markerTypes[0]);
        var markerFields = markerType.GetFields()
            .Where(handle => string.Equals(
                metadataReader.GetString(metadataReader.GetFieldDefinition(handle).Name),
                METADATA_FIELD_NAME,
                StringComparison.Ordinal))
            .ToList();
        if (markerFields.Count != 1)
        {
            throw new InvalidDataException(
                $"RPC metadata marker in assembly '{expectedAssemblyName}' must contain exactly one '{METADATA_FIELD_NAME}' field, but {markerFields.Count} were found.");
        }

        var constantHandle = metadataReader.GetFieldDefinition(markerFields[0]).GetDefaultValue();
        if (constantHandle.IsNil)
        {
            throw new InvalidDataException(
                $"RPC metadata field '{METADATA_FIELD_NAME}' in assembly '{expectedAssemblyName}' does not have a constant value.");
        }

        var constant = metadataReader.GetConstant(constantHandle);
        if (constant.TypeCode != ConstantTypeCode.String)
        {
            throw new InvalidDataException(
                $"RPC metadata field '{METADATA_FIELD_NAME}' in assembly '{expectedAssemblyName}' must be a string constant.");
        }

        var blobReader = metadataReader.GetBlobReader(constant.Value);
        var jsonContent = blobReader.ReadUTF16(blobReader.Length);
        var document = JsonSerializer.Deserialize<RpcMetadataDocument>(jsonContent, SerializerOptions)
                       ?? throw new InvalidDataException(
                           $"RPC metadata field '{METADATA_FIELD_NAME}' in assembly '{expectedAssemblyName}' contains an empty document.");

        if (!string.Equals(document.AssemblyName, expectedAssemblyName, StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                $"RPC metadata document expected assembly '{expectedAssemblyName}', but declares '{document.AssemblyName}'.");
        }

        document.Handlers = document.Handlers
            .OrderBy(handler => handler.ClientMethodName, StringComparer.Ordinal)
            .ToList();
        document.RelatedNamespaces = document.RelatedNamespaces
            .OrderBy(namespaceValue => namespaceValue, StringComparer.Ordinal)
            .ToList();

        return document;
    }

    private static bool IsMetadataMarker(MetadataReader metadataReader, TypeDefinitionHandle handle)
    {
        var typeDefinition = metadataReader.GetTypeDefinition(handle);
        return string.Equals(metadataReader.GetString(typeDefinition.Namespace), METADATA_TYPE_NAMESPACE, StringComparison.Ordinal)
               && string.Equals(metadataReader.GetString(typeDefinition.Name), METADATA_TYPE_NAME, StringComparison.Ordinal);
    }

    private static string SerializeMetadata(RpcMetadataDocument document)
    {
        return NormalizeLineEndings(JsonSerializer.Serialize(document, SerializerOptions));
    }

    private static string NormalizeLineEndings(string content)
    {
        return content.Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void WriteAtomically(string outputFilePath, string content)
    {
        var outputDirectory = Path.GetDirectoryName(outputFilePath)
                              ?? throw new InvalidOperationException(
                                  $"RPC metadata output path '{outputFilePath}' does not have a parent directory.");
        var temporaryFilePath = Path.Combine(
            outputDirectory,
            $".{Path.GetFileName(outputFilePath)}.{Guid.NewGuid():N}.tmp");

        try
        {
            // Keep readers from observing a truncated JSON document while the exporter is writing.
            File.WriteAllText(temporaryFilePath, content);
            File.Move(temporaryFilePath, outputFilePath, overwrite: true);
        }
        finally
        {
            File.Delete(temporaryFilePath);
        }
    }

    private static string ResolvePath(string path)
    {
        return Path.GetFullPath(path);
    }

    private static string ResolvePath(string basePath, string path)
    {
        return Path.IsPathRooted(path)
            ? Path.GetFullPath(path)
            : Path.GetFullPath(Path.Combine(basePath, path));
    }

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    private sealed class RpcMetadataDocument
    {
        public string AssemblyName { get; set; } = string.Empty;

        public string? DomainName { get; set; }

        public string? RoutePrefix { get; set; }

        public List<string> RelatedNamespaces { get; set; } = [];

        public List<HandlerMetadataDocument> Handlers { get; set; } = [];
    }

    private sealed class HandlerMetadataDocument
    {
        public string RequestType { get; set; } = string.Empty;

        public string ResponseType { get; set; } = string.Empty;

        public string HttpMethod { get; set; } = string.Empty;

        public string Route { get; set; } = string.Empty;

        public string ClientMethodName { get; set; } = string.Empty;

        public string HandlerType { get; set; } = string.Empty;

        public string Summary { get; set; } = string.Empty;
    }
}
