using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace Monica.Generators.AutoController.BuildTasks;

/// <summary>
/// Exports RPC metadata generated by <c>HttpApiControllerSourceGenerator</c> into a deterministic JSON file.
/// </summary>
public sealed partial class ExportRpcMetadataTask : Microsoft.Build.Utilities.Task
{
    private const string DefaultMetadataFileName = "__RpcMetadata.g.cs";

    [Required]
    public string ProjectDirectory { get; set; } = string.Empty;

    [Required]
    public string GeneratedFilesDirectory { get; set; } = string.Empty;

    public string MetadataFileName { get; set; } = DefaultMetadataFileName;

    [Required]
    public string OutputDirectory { get; set; } = string.Empty;

    public string? AssemblyName { get; set; }

    [Output]
    public string? OutputFilePath { get; private set; }

    public override bool Execute()
    {
        try
        {
            var projectDirectory = ResolvePath(ProjectDirectory);
            var generatedFilesDirectory = ResolvePath(projectDirectory, GeneratedFilesDirectory);
            var outputDirectory = ResolvePath(projectDirectory, OutputDirectory);
            var metadataFileName = string.IsNullOrWhiteSpace(MetadataFileName) ? DefaultMetadataFileName : MetadataFileName;

            if (!Directory.Exists(generatedFilesDirectory))
            {
                Log.LogError(
                    "RPC metadata export failed for project '{0}'. Generated files directory '{1}' does not exist. " +
                    "Ensure EmitCompilerGeneratedFiles is enabled and the project has already compiled.",
                    AssemblyName ?? Path.GetFileName(projectDirectory),
                    generatedFilesDirectory);
                return false;
            }

            var metadataFiles = Directory.GetFiles(generatedFilesDirectory, metadataFileName, SearchOption.AllDirectories);
            if (metadataFiles.Length == 0)
            {
                Log.LogError(
                    "RPC metadata export failed for project '{0}'. No '{1}' file was found under '{2}'.",
                    AssemblyName ?? Path.GetFileName(projectDirectory),
                    metadataFileName,
                    generatedFilesDirectory);
                return false;
            }

            var parsedFiles = new List<ParsedMetadataFile>();
            foreach (var filePath in metadataFiles)
            {
                if (TryParseMetadataFile(filePath, out var metadataFile, out var errorMessage))
                {
                    parsedFiles.Add(metadataFile!);
                    continue;
                }

                Log.LogWarning(
                    "Skipping RPC metadata candidate '{0}' because it could not be parsed: {1}",
                    filePath,
                    errorMessage);
            }

            if (parsedFiles.Count == 0)
            {
                Log.LogError(
                    "RPC metadata export failed for project '{0}'. Candidate files were found, but none contained valid metadata.",
                    AssemblyName ?? Path.GetFileName(projectDirectory));
                return false;
            }

            var selectedFile = SelectMetadataFile(parsedFiles);
            Directory.CreateDirectory(outputDirectory);

            var outputFilePath = Path.Combine(outputDirectory, $"{selectedFile.Document.AssemblyName}.rpc-metadata.json");
            var serializedContent = SerializeMetadata(selectedFile.Document);

            if (File.Exists(outputFilePath))
            {
                var currentContent = File.ReadAllText(outputFilePath);
                if (string.Equals(currentContent, serializedContent, StringComparison.Ordinal))
                {
                    OutputFilePath = outputFilePath;
                    Log.LogMessage(
                        MessageImportance.Low,
                        "RPC metadata is already up to date: {0}",
                        outputFilePath);
                    return true;
                }
            }

            File.WriteAllText(outputFilePath, serializedContent);
            OutputFilePath = outputFilePath;

            Log.LogMessage(
                MessageImportance.High,
                "Exported RPC metadata for '{0}' to '{1}'.",
                selectedFile.Document.AssemblyName,
                outputFilePath);
            return true;
        }
        catch (Exception ex)
        {
            Log.LogErrorFromException(ex, showStackTrace: true);
            return false;
        }
    }

    private ParsedMetadataFile SelectMetadataFile(List<ParsedMetadataFile> parsedFiles)
    {
        if (!string.IsNullOrWhiteSpace(AssemblyName))
        {
            var matchingAssemblyFiles = parsedFiles
                .Where(file => string.Equals(file.Document.AssemblyName, AssemblyName, StringComparison.Ordinal))
                .OrderByDescending(file => file.LastWriteTimeUtc)
                .ToList();

            if (matchingAssemblyFiles.Count > 0)
            {
                return matchingAssemblyFiles[0];
            }
        }

        return parsedFiles
            .OrderByDescending(file => file.LastWriteTimeUtc)
            .First();
    }

    private static bool TryParseMetadataFile(
        string filePath,
        out ParsedMetadataFile? metadataFile,
        out string? errorMessage)
    {
        try
        {
            var content = File.ReadAllText(filePath);
            var match = MetadataJsonRegex().Match(content);
            if (!match.Success)
            {
                metadataFile = null;
                errorMessage = "MetadataJson raw string literal was not found.";
                return false;
            }

            var jsonContent = match.Groups["json"].Value.Trim();
            var document = JsonSerializer.Deserialize<RpcMetadataDocument>(jsonContent, SerializerOptions)
                           ?? throw new InvalidOperationException("Metadata JSON was empty.");

            if (string.IsNullOrWhiteSpace(document.AssemblyName))
            {
                metadataFile = null;
                errorMessage = "AssemblyName was missing in metadata JSON.";
                return false;
            }

            document.Handlers = document.Handlers
                .OrderBy(handler => handler.ClientMethodName, StringComparer.Ordinal)
                .ToList();

            metadataFile = new ParsedMetadataFile(
                filePath,
                File.GetLastWriteTimeUtc(filePath),
                document);
            errorMessage = null;
            return true;
        }
        catch (Exception ex)
        {
            metadataFile = null;
            errorMessage = ex.Message;
            return false;
        }
    }

    private static string SerializeMetadata(RpcMetadataDocument document)
    {
        return JsonSerializer.Serialize(document, SerializerOptions);
    }

    private static string ResolvePath(string path)
    {
        return Path.GetFullPath(path);
    }

    private static string ResolvePath(string basePath, string path)
    {
        return Path.IsPathRooted(path)
            ? Path.GetFullPath(path)
            : Path.GetFullPath(Path.Combine(basePath, path));
    }

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    [GeneratedRegex("MetadataJson\\s*=\\s*\"\"\"(?<json>.+?)\"\"\";", RegexOptions.Singleline)]
    private static partial Regex MetadataJsonRegex();

    private sealed record ParsedMetadataFile(
        string FilePath,
        DateTime LastWriteTimeUtc,
        RpcMetadataDocument Document);

    private sealed class RpcMetadataDocument
    {
        public string AssemblyName { get; set; } = string.Empty;

        public string? DomainName { get; set; }

        public string? RoutePrefix { get; set; }

        public List<string> RelatedNamespaces { get; set; } = [];

        public List<HandlerMetadataDocument> Handlers { get; set; } = [];
    }

    private sealed class HandlerMetadataDocument
    {
        public string RequestType { get; set; } = string.Empty;

        public string ResponseType { get; set; } = string.Empty;

        public string HttpMethod { get; set; } = string.Empty;

        public string Route { get; set; } = string.Empty;

        public string ClientMethodName { get; set; } = string.Empty;

        public string HandlerType { get; set; } = string.Empty;

        public string Summary { get; set; } = string.Empty;
    }
}
