<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\common.xml"/>

  <PropertyGroup>
    <PackageDescription>Configuration management UI components for Monica framework, providing visual interfaces for managing application configuration and settings.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monica.Configuration\Monica.Configuration.csproj" />
    <ProjectReference Include="..\Monica.RegisterCentre\Monica.RegisterCentre.csproj" />
    <ProjectReference Include="..\Monica.Repository\Monica.Repository.csproj" />
    <ProjectReference Include="..\Monica.UI\Monica.UI.csproj" />
  </ItemGroup>
</Project>
