namespace MoLibrary.Generators.AutoController.Constants;

internal static class GeneratorConstants
{
    public static class AttributeNames
    {
        public const string Route = "Route";
        public const string Tags = "Tags";
        public const string HttpPost = "HttpPost";
        public const string HttpPut = "HttpPut";
        public const string HttpGet = "HttpGet";
        public const string HttpDelete = "HttpDelete";
        public const string HttpPatch = "HttpPatch";
        public const string FromForm = "FromForm";
        public const string FromQuery = "FromQuery";
        public const string FromBody = "FromBody";
        public const string ProducesResponseType = "ProducesResponseType";
        public const string ApiController = "ApiController";
    }

    public static class HandlerTypes
    {
        public const string Command = "Command";
        public const string Query = "Query";
        public const string CommandHandler = "CommandHandler";
        public const string QueryHandler = "QueryHandler";
    }

    public static class ClassNames
    {
        public const string ApplicationService = "ApplicationService";
        public const string ControllerBase = "ControllerBase";
    }

    public static class Namespaces
    {
        public const string GeneratedControllers = "GeneratedControllers";
    }

    public static readonly string[] BaseUsingStatements = [
        "Microsoft.AspNetCore.Mvc",
        "System.Net", 
        "System.Threading.Tasks",
        "MediatR",
        "MoLibrary.Core.Extensions",
        "MoLibrary.Tool.Extensions"
    ];

    public static class Templates
    {
        public const string AutoGeneratedComment = "// <auto-generated/>";
        public const string HttpApiControllerPrefix = "HttpApi";
    }

    public static class Documentation
    {
        public const string DocumentationPrefix = "///";
    }

    public static class ResponseTypes
    {
        public const string GenericResponseTemplate = "Res<{0}>";
    }
}