using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Monica.Generators.AutoController.Constants;
using Monica.Generators.AutoController.Diagnostics;
using Monica.Generators.AutoController.Models;

namespace Monica.Generators.AutoController.Generators;

internal static class ControllerCodeGenerator
{
    public static void Generate(SourceProductionContext context, IReadOnlyList<ControllerCandidate> candidates)
    {
        var duplicateCandidates = ReportDuplicateRoutes(context, candidates);
        foreach (var group in candidates
                     .Where(candidate => !duplicateCandidates.Contains(candidate))
                     .GroupBy(static candidate => new
                     {
                         candidate.Endpoint.ControllerRoute,
                         candidate.Endpoint.Domain,
                         candidate.Endpoint.RequestKind
                     }))
        {
            var controllerName = $"HttpEndpoint{group.Key.RequestKind}{group.Key.Domain}";
            context.AddSource($"{controllerName}.g.cs", GenerateController(
                controllerName,
                group.Key.ControllerRoute,
                group));
        }
    }

    private static HashSet<ControllerCandidate> ReportDuplicateRoutes(
        SourceProductionContext context,
        IReadOnlyList<ControllerCandidate> candidates)
    {
        var duplicates = new HashSet<ControllerCandidate>();
        foreach (var group in candidates.GroupBy(static candidate => new
                 {
                     candidate.Endpoint.HttpMethod,
                     candidate.Endpoint.NormalizedRoute
                 }).Where(static group => group.Count() > 1))
        {
            var names = string.Join(", ", group.Select(static candidate =>
                candidate.Endpoint.RequestDisplayName));
            foreach (var candidate in group)
            {
                duplicates.Add(candidate);
            }

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.DuplicateRoute,
                group.First().Endpoint.Location?.ToLocation() ?? Location.None,
                group.Key.HttpMethod.ToUpperInvariant(),
                group.First().Endpoint.CompleteRoute,
                names));
        }

        return duplicates;
    }

    private static string GenerateController(
        string controllerName,
        string controllerRoute,
        IEnumerable<ControllerCandidate> candidates)
    {
        var candidateList = candidates
            .OrderBy(static candidate => candidate.Endpoint.OperationName, StringComparer.Ordinal)
            .ToArray();
        var tags = candidateList.SelectMany(static candidate => candidate.Tags)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Net;");
        builder.AppendLine("using Microsoft.AspNetCore.Http;");
        builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
        builder.AppendLine("using Monica.Core.Mediator;");
        builder.AppendLine("using Monica.Core.Results;");
        builder.AppendLine("using Monica.DependencyInjection.Abstractions;");
        builder.AppendLine();
        builder.Append("namespace ").Append(GeneratorConstants.GENERATED_CONTROLLER_NAMESPACE).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("[global::Monica.Core.Execution.Mvc.MediatedController]");
        builder.Append("[Route(\"").Append(EscapeString(controllerRoute)).AppendLine("\")]");
        builder.AppendLine("[ApiController]");
        if (tags.Length > 0)
        {
            builder.Append("[Tags(")
                .Append(string.Join(", ", tags.Select(static tag => $"\"{EscapeString(tag)}\"")))
                .AppendLine(")]");
        }

        builder.Append("public sealed class ").Append(controllerName)
            .AppendLine("(IMediator mediator) : ControllerBase, ITransientDependency");
        builder.AppendLine("{");
        foreach (var candidate in candidateList)
        {
            AppendAction(builder, candidate.Endpoint);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendAction(StringBuilder builder, EndpointModel endpoint)
    {
        foreach (var line in endpoint.DocumentationComment.Split(new[] { "\r\n", "\n", "\r" }, StringSplitOptions.None))
        {
            builder.Append("    ").AppendLine(line);
        }

        builder.Append("    [Http").Append(endpoint.HttpMethod).Append("(\"")
            .Append(EscapeString(endpoint.RelativeRoute)).AppendLine("\")]");
        builder.Append("    [ProducesResponseType(typeof(").Append(endpoint.ResultTypeName)
            .AppendLine("), (int)HttpStatusCode.OK)]");
        builder.Append("    public async global::System.Threading.Tasks.Task<object> ")
            .Append(endpoint.OperationName).AppendLine("(");
        builder.Append("        [global::Monica.WebApi.AutoControllers.ModelBinding.ApiEndpointRequestAttribute(")
            .Append("global::Monica.WebApi.Annotations.ApiRequestBinding.")
            .Append(endpoint.Binding)
            .Append(")] ")
            .Append(endpoint.RequestTypeName).AppendLine(" request,");
        builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        return await mediator.Send(request, cancellationToken).GetResponse(this);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
