<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\common.xml"/>

  <PropertyGroup>
    <GenerateStaticWebAssetsManifest>true</GenerateStaticWebAssetsManifest>
    <NoWarn>$(NoWarn);CS1998</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Framework\MoLibrary.Framework.csproj" />
    <ProjectReference Include="..\MoLibrary.JobScheduler.UI\MoLibrary.JobScheduler.UI.csproj" />
    <ProjectReference Include="..\MoLibrary.UI\MoLibrary.UI.csproj" />
    <ProjectReference Include="..\MoLibrary.Logging\MoLibrary.Logging.csproj" />
  </ItemGroup>
</Project>
