window.monicaDesignData = {
  app: {
    name: "Monica",
    id: "MONICA.RUNTIME",
    version: "v1.0",
    environment: "Development",
    user: "Mo",
  },

  groups: [
    {
      id: "module",
      label: "Module",
      icon: "blocks",
      tone: "brass",
      items: [
        {
          id: "module-dashboard",
          label: "Module System Dashboard",
          icon: "layout-dashboard",
          route: "/module-system",
          description: "Monitor module lifecycle, health, performance, and dependency topology from one operational surface.",
        },
        {
          id: "dependency-injection",
          label: "Dependency Injection",
          icon: "git-fork",
          route: "/dependency-injection",
          description: "Inspect service registrations, lifetimes, resolution paths, and automatic registration diagnostics.",
        },
      ],
    },
    {
      id: "monitor",
      label: "Monitor",
      icon: "activity",
      tone: "moss",
      items: [
        { id: "system-info", label: "System Information", icon: "monitor-cog", route: "/system-info", description: "Review runtime identity, host characteristics, links, and process-level status." },
        { id: "runtime-metrics", label: "Runtime Metrics", icon: "gauge", route: "/runtime-metrics", description: "Observe live process, request, thread pool, and garbage collection signals." },
        { id: "otel-metrics", label: "OpenTelemetry Metrics", icon: "radio-tower", route: "/opentelemetry-metrics", description: "Explore exported meters, instruments, dimensions, and collection health." },
        { id: "memory-analysis", label: "Memory Analysis", icon: "memory-stick", route: "/memory-analysis", description: "Understand heap pressure, allocation behavior, and retained memory patterns." },
        { id: "service-discovery", label: "Service Discovery", icon: "radar", route: "/service-discovery", description: "Inspect discovered services, endpoints, health, and registration freshness." },
        { id: "execution-timing", label: "Execution Timing", icon: "timer-reset", route: "/execution-timing", description: "Trace timed operations and identify the execution paths consuming the most time." },
        { id: "logging-monitor", label: "Logging Monitor", icon: "scroll-text", route: "/logging-monitor", description: "Filter structured application events and correlate issues across modules." },
        { id: "project-units", label: "Project Units", icon: "component", route: "/project-units", description: "Review discovered ProjectUnits and the domain capabilities they contribute." },
        { id: "event-bus-monitor", label: "EventBus Monitor", icon: "webhook", route: "/eventbus-monitor", description: "Observe published events, handlers, delivery state, and recent failures." },
      ],
    },
    {
      id: "ai",
      label: "AI",
      icon: "bot",
      tone: "violet",
      items: [
        { id: "ai-assistant", label: "AI Assistant", icon: "message-square-text", route: "/ai/chat", description: "Work with configured models and Monica capabilities in one grounded conversation." },
        { id: "ai-providers", label: "AI Provider Management", icon: "network", route: "/ai/providers", description: "Configure provider endpoints, credentials, models, and availability checks." },
        { id: "ai-capabilities", label: "AI Capabilities", icon: "sparkles", route: "/ai/capabilities", description: "Manage tools, prompts, and capabilities available to Monica agents." },
        { id: "workflow", label: "Workflow", icon: "workflow", route: "/workflow", description: "Compose and observe repeatable AI-assisted workflows across Monica modules." },
      ],
    },
    {
      id: "knowledge",
      label: "Knowledge & Retrieval",
      shortLabel: "Knowledge",
      icon: "library-big",
      tone: "teal",
      items: [
        { id: "rag-indexing", label: "RAG Indexing", icon: "database-zap", route: "/rag/manage", description: "Build, refresh, and inspect retrieval indexes from registered data sources." },
        { id: "rag-debug", label: "RAG Debug", icon: "search-code", route: "/rag/debug", description: "Trace retrieval, ranking, chunking, and context assembly for a real query." },
        { id: "rag-chunkers", label: "RAG Chunker Management", icon: "split", route: "/rag/chunkers", description: "Compare and configure chunking strategies for different document shapes." },
        { id: "knowledge-bases", label: "Knowledge Bases", icon: "database", route: "/knowledge-bases", description: "Manage knowledge collections, source health, indexing state, and ownership." },
      ],
    },
    {
      id: "configuration",
      label: "Configuration",
      shortLabel: "Config",
      icon: "sliders-horizontal",
      tone: "amber",
      items: [
        { id: "config-state", label: "Configuration State", icon: "list-tree", route: "/configuration/state", description: "Inspect the effective configuration tree and the source of each value." },
        { id: "config-history", label: "Configuration History", icon: "history", route: "/configuration/history", description: "Review configuration changes, authors, timing, and affected environments." },
        { id: "config-versions", label: "Configuration Versions", icon: "git-compare-arrows", route: "/configuration/versions", description: "Compare versioned snapshots and promote a known state with confidence." },
        { id: "config-debug", label: "Configuration Debug", icon: "bug", route: "/configuration/debug", description: "Resolve overrides, missing keys, provider precedence, and validation failures." },
        { id: "config-storage", label: "Configuration Storage", icon: "hard-drive", route: "/configuration/storage", description: "Inspect storage providers, connectivity, cache state, and persistence health." },
        { id: "data-channel", label: "DataChannel Management", icon: "cable", route: "/data-channel", description: "Manage data channels, endpoints, synchronization, and delivery status." },
      ],
    },
    {
      id: "debug",
      label: "Debug",
      icon: "bug",
      tone: "coral",
      items: [
        { id: "signalr-debug", label: "SignalR Debug", icon: "radio", route: "/signalr-debug", description: "Test hubs, connections, invocations, and real-time message delivery." },
        { id: "mapper-debug", label: "Mapper Debug", icon: "shuffle", route: "/mapper-debug", description: "Inspect object mapping plans, member resolution, and conversion results." },
        { id: "observable-instance", label: "Observable Instance", icon: "eye", route: "/observable-instance", description: "Track registered instances and watch state transitions as they happen." },
        { id: "state-store", label: "State Store Management", icon: "database", route: "/state-store", description: "Query state keys, storage metadata, expiration, and provider behavior." },
        { id: "diff-highlight", label: "Text Diff Comparison", icon: "file-diff", route: "/diff-highlight", description: "Compare text with side-by-side, inline, character, and export views." },
        { id: "repository-diagnostics", label: "Repository Diagnostics", icon: "stethoscope", route: "/repository-diagnostics", description: "Examine repository behavior, query paths, and persistence diagnostics." },
      ],
    },
    {
      id: "scheduling",
      label: "Task Scheduling",
      shortLabel: "Jobs",
      icon: "calendar-clock",
      tone: "blue",
      items: [
        { id: "jobs-dashboard", label: "Dashboard", icon: "layout-dashboard", route: "/job-scheduler", description: "See scheduler health, throughput, upcoming work, and recent outcomes." },
        { id: "jobs-monitor", label: "Real-time Monitor", icon: "radio-tower", route: "/job-scheduler/monitor", description: "Follow executing jobs, workers, leases, and state transitions in real time." },
        { id: "job-definitions", label: "Job Definitions", icon: "list-checks", route: "/job-scheduler/definitions", description: "Create and inspect recurring or triggered job definitions and schedules." },
        { id: "job-instances", label: "Job Instances", icon: "layers-3", route: "/job-scheduler/instances", description: "Review concrete job instances, attempts, timing, and terminal state." },
        { id: "job-statistics", label: "Statistics", icon: "chart-no-axes-combined", route: "/job-scheduler/statistics", description: "Analyze scheduler reliability, duration distribution, and execution trends." },
      ],
    },
    {
      id: "infrastructure",
      label: "Infrastructure",
      shortLabel: "Infra",
      icon: "server-cog",
      tone: "steel",
      items: [
        { id: "git-repositories", label: "Git Repositories", icon: "git-branch", route: "/git", description: "Manage working repositories, branch state, remotes, and recent operations." },
        { id: "file-ops", label: "FileOps Workspace", icon: "folder-code", route: "/file-ops", description: "Work safely with scoped files, transfers, and filesystem operations." },
        { id: "terminal", label: "Terminal", icon: "square-terminal", route: "/terminal", description: "Open a managed command surface in the current Monica environment." },
        { id: "k8s", label: "K8S Operations", icon: "container", route: "/k8s", description: "Inspect Kubernetes resources, workloads, namespaces, and operational health." },
        { id: "utilities", label: "Utilities Toolbox", icon: "wrench", route: "/utilities", description: "Use focused developer utilities without leaving the Monica workspace." },
      ],
    },
    {
      id: "documentation",
      label: "Documentation",
      shortLabel: "Docs",
      icon: "book-open",
      tone: "rose",
      items: [
        { id: "markdown-library", label: "Markdown Library", icon: "library", route: "/markdown", description: "Read registered Markdown documentation with outline, search, and rich rendering." },
      ],
    },
  ],

  profiles: {
    module: {
      eyebrow: "MODULE / RUNTIME",
      status: "All systems nominal",
      statusTone: "success",
      action: "Refresh runtime",
      tabs: ["System Overview", "Performance Monitoring", "Module Management", "Dependencies", "Assembly Analysis"],
      metrics: [
        { label: "Registered modules", value: "42", detail: "+3 this branch", trend: "up" },
        { label: "Enabled", value: "40", detail: "95.2% available", trend: "steady" },
        { label: "Initialization", value: "318 ms", detail: "42 ms below baseline", trend: "down" },
        { label: "Dependency edges", value: "126", detail: "0 circular paths", trend: "steady" },
      ],
      posture: {
        score: "99.8",
        label: "Runtime posture",
        summary: "Registration, initialization, and dependency checks are inside the expected envelope.",
        facts: [
          ["Started", "16:11:42"],
          ["Environment", "Development"],
          ["Web runtime", "Active"],
        ],
      },
      ledgerTitle: "Initialization ledger",
      ledger: [
        ["Monica.Core", "Foundation", "Healthy", "31 ms"],
        ["Monica.UI", "Presentation", "Healthy", "46 ms"],
        ["Monica.Framework", "Infrastructure", "Healthy", "54 ms"],
        ["Monica.AI", "Intelligence", "Healthy", "82 ms"],
        ["Monica.JobScheduler", "Operations", "Healthy", "39 ms"],
      ],
      activity: [
        ["Module graph reconciled", "126 dependency edges verified", "2 min"],
        ["Configuration snapshot accepted", "Version dev.2026.07.18.4", "12 min"],
        ["Telemetry exporter connected", "OTLP endpoint is responding", "18 min"],
      ],
    },

    monitor: {
      eyebrow: "OBSERVABILITY / LIVE",
      status: "Signals flowing",
      statusTone: "success",
      action: "Capture snapshot",
      tabs: ["Overview", "Live signals", "Diagnostics", "Exports"],
      metrics: [
        { label: "CPU", value: "18.4%", detail: "7 min average", trend: "steady" },
        { label: "Managed memory", value: "642 MB", detail: "Gen 2 stable", trend: "steady" },
        { label: "Request rate", value: "184/s", detail: "+8.2% today", trend: "up" },
        { label: "Uptime", value: "6h 42m", detail: "No restarts", trend: "steady" },
      ],
      posture: {
        score: "98.6",
        label: "Signal confidence",
        summary: "Core runtime, application, and export signals are fresh and within policy.",
        facts: [["Meters", "18 active"], ["Export lag", "1.2 s"], ["Dropped points", "0"]],
      },
      ledgerTitle: "Signal ledger",
      ledger: [
        ["http.server.duration", "Histogram", "Healthy", "184/s"],
        ["process.runtime.dotnet.gc", "Counter", "Healthy", "2.1/s"],
        ["monica.module.init", "Histogram", "Healthy", "42 points"],
        ["monica.jobs.duration", "Histogram", "Healthy", "8 points"],
        ["aspnetcore.connections", "Gauge", "Healthy", "14 open"],
      ],
      activity: [
        ["Runtime snapshot completed", "18 meters sampled", "1 min"],
        ["GC pressure returned to baseline", "Pause ratio now 0.7%", "9 min"],
        ["Service discovery refreshed", "12 endpoints healthy", "21 min"],
      ],
    },

    ai: {
      eyebrow: "INTELLIGENCE / CAPABILITIES",
      status: "3 providers ready",
      statusTone: "success",
      action: "New conversation",
      tabs: ["Overview", "Providers", "Capabilities", "Recent runs"],
      metrics: [
        { label: "Providers", value: "3", detail: "All reachable", trend: "steady" },
        { label: "Models", value: "11", detail: "4 tool-capable", trend: "up" },
        { label: "Capabilities", value: "27", detail: "2 recently added", trend: "up" },
        { label: "Median latency", value: "1.8 s", detail: "P50, last hour", trend: "down" },
      ],
      posture: {
        score: "97.4",
        label: "Capability readiness",
        summary: "Provider health and capability discovery are stable across the active model estate.",
        facts: [["Primary", "OpenAI"], ["Tool calls", "96.1% success"], ["Queued runs", "2"]],
      },
      ledgerTitle: "Provider estate",
      ledger: [
        ["OpenAI", "Primary", "Healthy", "824 ms"],
        ["Azure OpenAI", "Fallback", "Healthy", "1.2 s"],
        ["Local inference", "Development", "Healthy", "2.7 s"],
        ["Retrieval tools", "Capability set", "Healthy", "8 tools"],
        ["Developer tools", "Capability set", "Healthy", "12 tools"],
      ],
      activity: [
        ["Capability catalog refreshed", "27 capabilities available", "4 min"],
        ["Provider probe completed", "All model endpoints reachable", "11 min"],
        ["Workflow run finished", "Release summary / 9 steps", "26 min"],
      ],
    },

    knowledge: {
      eyebrow: "KNOWLEDGE / RETRIEVAL",
      status: "Indexes current",
      statusTone: "success",
      action: "Start indexing",
      tabs: ["Collections", "Index runs", "Retrieval quality", "Sources"],
      metrics: [
        { label: "Knowledge bases", value: "8", detail: "6 production ready", trend: "steady" },
        { label: "Indexed chunks", value: "128k", detail: "+4,280 today", trend: "up" },
        { label: "Freshness", value: "97.9%", detail: "Within 24 hours", trend: "up" },
        { label: "Recall @ 10", value: "0.91", detail: "+0.03 this week", trend: "up" },
      ],
      posture: {
        score: "97.9",
        label: "Knowledge freshness",
        summary: "Sources are synchronized and retrieval evaluation remains above the target envelope.",
        facts: [["Last index", "7 min ago"], ["Pending files", "14"], ["Failed sources", "0"]],
      },
      ledgerTitle: "Collection health",
      ledger: [
        ["Monica documentation", "Markdown", "Healthy", "42.8k chunks"],
        ["Architecture records", "Git", "Healthy", "8.4k chunks"],
        ["Runbooks", "Markdown", "Healthy", "11.2k chunks"],
        ["API references", "Generated", "Healthy", "51.7k chunks"],
        ["Release notes", "Git", "Indexing", "14.1k chunks"],
      ],
      activity: [
        ["Incremental index completed", "4,280 chunks refreshed", "7 min"],
        ["Retrieval evaluation passed", "Recall @ 10 reached 0.91", "34 min"],
        ["Source watcher connected", "8 collections under watch", "1 hr"],
      ],
    },

    configuration: {
      eyebrow: "CONFIGURATION / GOVERNANCE",
      status: "State verified",
      statusTone: "success",
      action: "Create snapshot",
      tabs: ["Effective state", "Sources", "History", "Validation"],
      metrics: [
        { label: "Effective keys", value: "286", detail: "12 providers", trend: "steady" },
        { label: "Overrides", value: "31", detail: "All attributed", trend: "steady" },
        { label: "Current version", value: "dev.4", detail: "12 min old", trend: "up" },
        { label: "Validation", value: "100%", detail: "0 rejected values", trend: "steady" },
      ],
      posture: {
        score: "100",
        label: "Configuration integrity",
        summary: "The effective state is attributed, versioned, and valid against registered option contracts.",
        facts: [["Environment", "Development"], ["Providers", "12"], ["Drift", "None"]],
      },
      ledgerTitle: "Configuration providers",
      ledger: [
        ["appsettings.json", "File", "Healthy", "142 keys"],
        ["appsettings.Development", "File", "Healthy", "38 keys"],
        ["Environment variables", "Process", "Healthy", "21 keys"],
        ["Monica storage", "Remote", "Healthy", "74 keys"],
        ["User secrets", "Development", "Healthy", "11 keys"],
      ],
      activity: [
        ["Snapshot dev.4 accepted", "286 effective keys", "12 min"],
        ["Option validation completed", "42 contracts passed", "12 min"],
        ["Storage provider synchronized", "No configuration drift", "28 min"],
      ],
    },

    debug: {
      eyebrow: "DEBUG / INSPECTION",
      status: "Diagnostics ready",
      statusTone: "info",
      action: "Open session",
      tabs: ["Workspace", "Active sessions", "Recent captures", "Exports"],
      metrics: [
        { label: "Active sessions", value: "4", detail: "2 local connections", trend: "steady" },
        { label: "Captured events", value: "1,842", detail: "Last 60 minutes", trend: "up" },
        { label: "Warnings", value: "3", detail: "No critical issues", trend: "steady" },
        { label: "Storage", value: "28 MB", detail: "Auto-prune enabled", trend: "steady" },
      ],
      posture: {
        score: "96.2",
        label: "Diagnostic coverage",
        summary: "Core debug surfaces are connected and no capture path is reporting a terminal failure.",
        facts: [["SignalR", "Connected"], ["State watches", "8"], ["Retention", "24 hours"]],
      },
      ledgerTitle: "Diagnostic surfaces",
      ledger: [
        ["SignalR Debug", "Real time", "Healthy", "2 sessions"],
        ["Observable Instance", "State", "Healthy", "8 watches"],
        ["Mapper Debug", "Transform", "Healthy", "4 plans"],
        ["State Store", "Persistence", "Healthy", "124 keys"],
        ["Repository Diagnostics", "Data", "Warning", "3 notices"],
      ],
      activity: [
        ["SignalR session connected", "debug-ui / local", "3 min"],
        ["State capture exported", "124 keys / JSON", "18 min"],
        ["Mapper plan inspected", "UserProfile → UserProfileDto", "25 min"],
      ],
    },

    scheduling: {
      eyebrow: "SCHEDULING / OPERATIONS",
      status: "Workers on schedule",
      statusTone: "success",
      action: "Create job",
      tabs: ["Overview", "Live monitor", "Definitions", "Instances", "Statistics"],
      metrics: [
        { label: "Definitions", value: "24", detail: "18 recurring", trend: "steady" },
        { label: "Running", value: "3", detail: "Across 4 workers", trend: "up" },
        { label: "Success rate", value: "99.4%", detail: "Last 24 hours", trend: "up" },
        { label: "Next dispatch", value: "00:42", detail: "CacheWarmupJob", trend: "steady" },
      ],
      posture: {
        score: "99.4",
        label: "Schedule reliability",
        summary: "Workers are leased, dispatch latency is low, and failure rate remains under the target threshold.",
        facts: [["Workers", "4 online"], ["Queue depth", "7"], ["Lease health", "Stable"]],
      },
      ledgerTitle: "Upcoming work",
      ledger: [
        ["CacheWarmupJob", "Recurring", "Scheduled", "in 42 sec"],
        ["TelemetryRollupJob", "Recurring", "Running", "18 sec elapsed"],
        ["KnowledgeIndexJob", "Triggered", "Queued", "position 2"],
        ["ConfigSnapshotJob", "Recurring", "Scheduled", "in 14 min"],
        ["RetentionCleanupJob", "Recurring", "Healthy", "1 hr ago"],
      ],
      activity: [
        ["TelemetryRollupJob started", "Worker mo-worker-02", "18 sec"],
        ["CacheWarmupJob completed", "412 ms / attempt 1", "4 min"],
        ["KnowledgeIndexJob queued", "Triggered by source change", "8 min"],
      ],
    },

    infrastructure: {
      eyebrow: "INFRASTRUCTURE / WORKSPACES",
      status: "Connections healthy",
      statusTone: "success",
      action: "Open workspace",
      tabs: ["Overview", "Connections", "Recent operations", "Policies"],
      metrics: [
        { label: "Repositories", value: "12", detail: "3 with changes", trend: "steady" },
        { label: "K8S contexts", value: "4", detail: "All reachable", trend: "steady" },
        { label: "Workspaces", value: "7", detail: "2 active now", trend: "up" },
        { label: "Operations", value: "184", detail: "Last 24 hours", trend: "up" },
      ],
      posture: {
        score: "98.1",
        label: "Connection posture",
        summary: "Repository, filesystem, terminal, and cluster integrations are available inside their configured scopes.",
        facts: [["Default repo", "MoLibrary"], ["Cluster", "mo-dev"], ["Policy", "Scoped"]],
      },
      ledgerTitle: "Connected workspaces",
      ledger: [
        ["MoLibrary", "Git repository", "Healthy", "dev"],
        ["Monica docs", "File workspace", "Healthy", "42 files"],
        ["mo-dev", "Kubernetes", "Healthy", "18 pods"],
        ["Local terminal", "Shell", "Healthy", "zsh"],
        ["Artifacts", "FileOps", "Healthy", "1.8 GB"],
      ],
      activity: [
        ["Repository status refreshed", "MoLibrary / 3 modified files", "2 min"],
        ["Cluster probe completed", "18 of 18 pods ready", "14 min"],
        ["Workspace policy evaluated", "No scope violations", "22 min"],
      ],
    },

    documentation: {
      eyebrow: "DOCUMENTATION / LIBRARY",
      status: "Library indexed",
      statusTone: "success",
      action: "Open library",
      tabs: ["Recently viewed", "Collections", "Bookmarks", "Search"],
      metrics: [
        { label: "Documents", value: "214", detail: "12 collections", trend: "up" },
        { label: "Coverage", value: "92%", detail: "Public modules", trend: "up" },
        { label: "Updated", value: "18", detail: "This week", trend: "up" },
        { label: "Bookmarks", value: "27", detail: "4 shared", trend: "steady" },
      ],
      posture: {
        score: "92",
        label: "Documentation coverage",
        summary: "Core module guides are available, searchable, and linked to their owning Monica packages.",
        facts: [["Collections", "12"], ["Broken links", "0"], ["Last index", "6 min ago"]],
      },
      ledgerTitle: "Recently updated",
      ledger: [
        ["Module development guide", "Architecture", "Published", "12 min"],
        ["UI theme contract", "UI", "Published", "1 hr"],
        ["Job scheduler operations", "Operations", "Published", "3 hr"],
        ["RAG indexing guide", "AI", "Review", "Yesterday"],
        ["Configuration reference", "Framework", "Published", "Yesterday"],
      ],
      activity: [
        ["Library index refreshed", "214 documents searchable", "6 min"],
        ["Module guide published", "Module development guide", "12 min"],
        ["Broken-link scan passed", "1,842 links checked", "41 min"],
      ],
    },
  },

  notifications: [
    { tone: "success", title: "Module graph verified", detail: "126 dependency edges checked with no circular path.", time: "2 min ago" },
    { tone: "info", title: "Configuration snapshot ready", detail: "Development snapshot dev.2026.07.18.4 is active.", time: "12 min ago" },
    { tone: "warning", title: "Three diagnostic notices", detail: "Repository diagnostics found non-blocking query hints.", time: "28 min ago" },
  ],
};
