<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.xml"/>
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\MoLibrary.Core\MoLibrary.Core.csproj"/>
		<ProjectReference Include="..\..\MoLibrary.Repository\MoLibrary.Repository.csproj"/>
		<ProjectReference Include="..\Test.MoLibrary\Test.MoLibrary.csproj"/>
	</ItemGroup>

</Project> 