<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />

  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.RegisterCentre\Monica.RegisterCentre.csproj" />
  </ItemGroup>
</Project>
