<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageDescription>Dynamic configuration management for Monica framework with support for runtime configuration updates and distributed configuration sources.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.ServiceDiscovery\Monica.ServiceDiscovery.csproj" />
  </ItemGroup>
</Project>
