<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageDescription>Dapr integration for Monica framework providing distributed application runtime capabilities including actors, pub/sub, state management, and service invocation.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.AspNetCore" Version="1.18.4" />
    <PackageReference Include="Dapr.Client" Version="1.18.4" />
    <PackageReference Include="Dapr.DistributedLock" Version="1.18.4" />
    <PackageReference Include="Dapr.Messaging" Version="1.18.4" />
	<PackageReference Include="Dapr.Actors.AspNetCore" Version="1.18.4" />
	<PackageReference Include="Dapr.Actors" Version="1.18.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.WebApi\Monica.WebApi.csproj" />
    <ProjectReference Include="..\Monica.EventBus\Monica.EventBus.csproj" />
    <ProjectReference Include="..\Monica.Locker\Monica.Locker.csproj" />
    <ProjectReference Include="..\Monica.ServiceDiscovery\Monica.ServiceDiscovery.csproj" />
    <ProjectReference Include="..\Monica.StateStore\Monica.StateStore.csproj" />
  </ItemGroup>
</Project>
