using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Monica.Framework.Generators.AlterItemGenerator;

/// <summary>
/// Code builder for generating the change-item data class and Apply method.
/// </summary>
internal class CodeBuilder
{
    /// <summary>
    /// Generate complete code for the change-item data class.
    /// </summary>
    public string BuildAlterItemDataClass(
        EntityAnalysisResult analysisResult, 
        FlattenedPropertyResult flattenedResult,
        string? customNamespace = null,
        string? customClassName = null,
        bool includeDebugInfo = false)
    {
        var entitySymbol = analysisResult.EntitySymbol;
        var entityName = entitySymbol.Name;
        var entityNamespace = entitySymbol.ContainingNamespace.ToDisplayString();
        var className = customClassName ?? $"{entityName}AlterItemDataGen";
        var namespaceName = customNamespace ?? $"{entityNamespace}";

        var sb = new StringBuilder();

        // File headers and using statements
        BuildFileHeader(sb, entitySymbol, includeDebugInfo);
        BuildUsingStatements(sb, entitySymbol, flattenedResult);

        // namespace start
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Class definition begins
        BuildClassHeader(sb, className, entityName, includeDebugInfo);

        // Property definition
        BuildProperties(sb, flattenedResult);

        // Apply method
        BuildApplyMethod(sb, entityName, flattenedResult);
        
        // GetChanges method
        BuildGetChangesMethod(sb, entityName, flattenedResult);

        // End of class definition
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Build file header
    /// </summary>
    private void BuildFileHeader(StringBuilder sb, INamedTypeSymbol entitySymbol, bool includeDebugInfo)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by Monica.Framework.Generators.AlterItemDataGenerator");
        
        if (includeDebugInfo)
        {
            sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Source entity: {entitySymbol.ToDisplayString()}");
        }
        
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    /// <summary>
    /// Build using statements.
    /// </summary>
    private void BuildUsingStatements(StringBuilder sb, INamedTypeSymbol entitySymbol, FlattenedPropertyResult flattenedResult)
    {
        var usings = new HashSet<string>
        {
            "System",
            "System.Collections.Generic",
            "System.ComponentModel.DataAnnotations",
            "System.Text.Json.Serialization",
            "Monica.Framework.ChangeTracking.Abstractions"
        };

        // Add entity namespace
        var entityNamespace = entitySymbol.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(entityNamespace))
        {
            usings.Add(entityNamespace);
        }

        // Add namespace related to attribute type
        foreach (var property in flattenedResult.Properties)
        {
            AddNamespacesFromProperty(usings, property);
        }

        foreach (var group in flattenedResult.NavigationGroups)
        {
            foreach (var property in group.Properties)
            {
                AddNamespacesFromProperty(usings, property);
            }
        }

        var sortedUsings = usings.OrderBy(u => u == "System" ? "0" : u).ToList();
        foreach (var usingStatement in sortedUsings)
        {
            sb.AppendLine($"using {usingStatement};");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Add related namespace from FlattenedProperty
    /// </summary>
    private void AddNamespacesFromProperty(HashSet<string> usings, FlattenedProperty property)
    {
        // Extract the namespace from the type of the original attribute symbol
        var typeSymbol = property.OriginalPropertySymbol.Type;
        AddNamespacesFromTypeSymbol(usings, typeSymbol);
    }
    
    /// <summary>
    /// Add namespace from type symbol
    /// </summary>
    private static void AddNamespacesFromTypeSymbol(HashSet<string> usings, ITypeSymbol typeSymbol)
    {
        // Handling nullable types
        if (typeSymbol is INamedTypeSymbol namedType && 
            namedType.IsGenericType && 
            namedType.OriginalDefinition.ToDisplayString() == "System.Nullable<T>")
        {
            AddNamespacesFromTypeSymbol(usings, namedType.TypeArguments[0]);
            return;
        }
        
        // Add the namespace where the type is located
        var namespaceName = typeSymbol.ContainingNamespace?.ToDisplayString();
        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
        {
            usings.Add(namespaceName!);
        }
        
        // Handling generic type parameters
        if (typeSymbol is INamedTypeSymbol genericType && genericType.IsGenericType)
        {
            foreach (var typeArg in genericType.TypeArguments)
            {
                AddNamespacesFromTypeSymbol(usings, typeArg);
            }
        }
    }

    /// <summary>
    /// Get a compact type display string without using the global:: prefix
    /// </summary>
    private string GetConciseTypeString(ITypeSymbol typeSymbol)
    {
        // Create a concise display format without using fully qualified names
        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes
        );
        
        var typeName = typeSymbol.ToDisplayString(format);
        
        // Make sure all reference and value types are nullable
        if (!typeName.EndsWith("?"))
        {
            // For value types, if not already Nullable<T>, add ?
            if (!typeSymbol.IsReferenceType)
            {
                if (typeSymbol is INamedTypeSymbol namedType && 
                    namedType.IsGenericType && 
                    namedType.OriginalDefinition.ToDisplayString() == "System.Nullable<T>")
                {
                    // Already Nullable<T>, leave it as is
                    return typeName;
                }

                return typeName + "?";
            }

            // For reference types (including string), add ?
            return typeName + "?";
        }
        
        return typeName;
    }

    /// <summary>
    /// Build class header
    /// </summary>
    private void BuildClassHeader(StringBuilder sb, string className, string entityName, bool includeDebugInfo)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Change-item data for the {entityName} entity.");
        sb.AppendLine("/// </summary>");
        
        if (includeDebugInfo)
        {
            sb.AppendLine("/// <remarks>");
            sb.AppendLine("/// This type is generated by the source generator. Do not modify it manually.");
            sb.AppendLine("/// </remarks>");
        }
        
        sb.AppendLine($"public partial class {className} : IChangeItemData<{entityName}>");
        sb.AppendLine("{");
    }

    /// <summary>
    /// Build property definition
    /// </summary>
    private void BuildProperties(StringBuilder sb, FlattenedPropertyResult flattenedResult)
    {
        // Grouping attributes: direct attributes and navigation attributes are processed separately
        var directProperties = flattenedResult.Properties.Where(p => !p.IsOptionalNavigation).ToList();
        var propertyGroups = GroupPropertiesByOwner(directProperties);
        
        // Generate direct attributes (no grouping)
        foreach (var property in propertyGroups.Where(g => g.Key == "Direct").SelectMany(g => g.Value))
        {
            BuildPropertyDeclaration(sb, property);
        }
        
        // Generate grouping properties
        foreach (var group in propertyGroups.Where(g => g.Key != "Direct"))
        {
            sb.AppendLine($"    #region {group.Key}");
            sb.AppendLine();
            
            foreach (var property in group.Value)
            {
                BuildPropertyDeclaration(sb, property);
            }
            
            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }
        
        // Generate navigation attribute group
        foreach (var navGroup in flattenedResult.NavigationGroups)
        {
            sb.AppendLine($"    #region {navGroup.NavigationPropertyName}");
            sb.AppendLine();
            
            foreach (var property in navGroup.Properties)
            {
                BuildPropertyDeclaration(sb, property);
            }
            
            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Building the Apply method and the GenedApply method
    /// </summary>
    private void BuildApplyMethod(StringBuilder sb, string entityName, FlattenedPropertyResult flattenedResult)
    {
        // Generate virtual Apply method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 应用变更到目标实体 (可被重写以扩展功能)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entity\">目标 {entityName} 实体</param>");
        sb.AppendLine($"    public virtual void Apply({entityName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        GenedApply(entity);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate the GenedApply method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 生成的应用变更逻辑 (由Source Generator自动生成)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entity\">目标 {entityName} 实体</param>");
        sb.AppendLine($"    protected void GenedApply({entityName} entity)");
        sb.AppendLine("    {");

        // Handle direct properties (properties flattened from Owned type)
        var directProperties = flattenedResult.Properties.Where(p => !p.IsOptionalNavigation).ToList();
        var propertyGroups = GroupPropertiesByOwner(directProperties);
        
        // Generate direct property assignment (no grouping)
        foreach (var property in propertyGroups.Where(g => g.Key == "Direct").SelectMany(g => g.Value))
        {
            BuildPropertyAssignment(sb, property);
        }
        
        // Generate grouping attribute assignments
        foreach (var group in propertyGroups.Where(g => g.Key != "Direct"))
        {
            sb.AppendLine($"        #region {group.Key}");
            sb.AppendLine();
            
            foreach (var property in group.Value)
            {
                BuildPropertyAssignment(sb, property);
            }
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
        }
        
        // Handling navigation property groups
        foreach (var group in flattenedResult.NavigationGroups)
        {
            BuildNavigationPropertyGroup(sb, group);
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Build attribute assignment code
    /// </summary>
    private void BuildPropertyAssignment(StringBuilder sb, FlattenedProperty property)
    {
        sb.AppendLine($"        if ({property.Name} != null)");
        sb.AppendLine("        {");

        // Handling special cases: DateTime default value checking
        if (IsDateTimeType(property.Type))
        {
            // Check if original property is nullable
            if (property.OriginalType.Contains("?") || property.OriginalType.StartsWith("DateTime?"))
            {

                // Target property is nullable, default value needs to be checked and converted
                sb.AppendLine($"            if ({property.Name} != default(DateTime))");
                sb.AppendLine("            {");
                var safePropertyPath = property.PropertyPath.Contains('.') ? MakeNonNullPropertyPath(property.PropertyPath) : property.PropertyPath;
                sb.AppendLine($"                entity.{safePropertyPath} = {property.Name}.Value;");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                entity.{safePropertyPath} = null;");
                sb.AppendLine("            }");
                
            }
            else
            {
                // The target attribute is non-null and can be assigned directly.
                var safePropertyPath = property.PropertyPath.Contains('.') ? MakeNonNullPropertyPath(property.PropertyPath) : property.PropertyPath;
                sb.AppendLine($"            entity.{safePropertyPath} = {property.Name}.Value;");
            }
        }
        else if (IsNullableValueType(property.Type))
        {
            var safePropertyPath = property.PropertyPath.Contains('.') ? MakeNonNullPropertyPath(property.PropertyPath) : property.PropertyPath;
            sb.AppendLine($"            entity.{safePropertyPath} = {property.Name}.Value;");
        }
        else
        {
            var safePropertyPath = property.PropertyPath.Contains('.') ? MakeNonNullPropertyPath(property.PropertyPath) : property.PropertyPath;
            sb.AppendLine($"            entity.{safePropertyPath} = {property.Name};");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Build navigation property group code
    /// </summary>
    private void BuildNavigationPropertyGroup(StringBuilder sb, NavigationPropertyGroup group)
    {
        sb.AppendLine($"        #region {group.NavigationPropertyName}");
        sb.AppendLine();
        
        // Generate check array and condition
        var propertyNames = group.Properties.Select(p => p.Name).ToList();
        sb.AppendLine($"        object?[] {group.NavigationPropertyName.ToLower()}List = [{string.Join(", ", propertyNames)}];");
        sb.AppendLine($"        if ({group.NavigationPropertyName.ToLower()}List.Any(x => x != null))");
        sb.AppendLine("        {");
        sb.AppendLine($"            entity.{group.NavigationPropertyName} ??= new {GetNavigationPropertyType(group)}();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate a single property assignment
        foreach (var property in group.Properties)
        {
            BuildPropertyAssignment(sb, property);
            // sb.AppendLine($"        if ({property.Name} != null)");
            // sb.AppendLine("        {");
            //
            // if (IsDateTimeType(property.Type))
            // {
            // // Check if the original property is nullable
            //     if (property.OriginalType.Contains("?") || property.OriginalType.StartsWith("DateTime?"))
            //     {
            // // The target attribute is nullable and can be assigned directly.
            //         var safePropertyPath = MakeNonNullPropertyPath(property.PropertyPath);
            //         sb.AppendLine($"            entity.{safePropertyPath} = {property.Name};");
            //     }
            //     else
            //     {
            // // The target attribute is non-null and needs to check the default value and convert it
            //         sb.AppendLine($"            if ({property.Name} != default(DateTime))");
            //         sb.AppendLine("            {");
            //         var safePropertyPath = MakeNonNullPropertyPath(property.PropertyPath);
            //         sb.AppendLine($"                entity.{safePropertyPath} = {property.Name}.Value;");
            //         sb.AppendLine("            }");
            //     }
            // }
            // else if (IsNullableValueType(property.Type))
            // {
            //     var safePropertyPath = MakeNonNullPropertyPath(property.PropertyPath);
            //     sb.AppendLine($"            entity.{safePropertyPath} = {property.Name}.Value;");
            // }
            // else
            // {
            //     var safePropertyPath = MakeNonNullPropertyPath(property.PropertyPath);
            //     sb.AppendLine($"            entity.{safePropertyPath} = {property.Name};");
            // }
            //
            // sb.AppendLine("        }");
            // sb.AppendLine();
        }

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    /// <summary>
    /// Get navigation attribute type
    /// </summary>
    private string GetNavigationPropertyType(NavigationPropertyGroup group)
    {
        // Use the actual type name obtained from the symbol information
        return group.NavigationPropertyTypeName;
    }

    /// <summary>
    /// Check if it is of DateTime type
    /// </summary>
    private bool IsDateTimeType(string type)
    {
        return type.Contains("DateTime") && !type.Contains("Offset");
    }

    /// <summary>
    /// Check if it is a nullable value type
    /// </summary>
    private bool IsNullableValueType(string type)
    {
        return type.EndsWith("?") && 
               !type.StartsWith("string") && 
               !type.Contains("List<") &&
               !type.Contains("IList<");
    }
    
    /// <summary>
    /// Group properties based on property path
    /// </summary>
    private Dictionary<string, List<FlattenedProperty>> GroupPropertiesByOwner(List<FlattenedProperty> properties)
    {
        var groups = new Dictionary<string, List<FlattenedProperty>>();
        
        foreach (var property in properties)
        {
            var groupName = GetOwnerGroupName(property.PropertyPath);
            
            if (!groups.ContainsKey(groupName))
            {
                groups[groupName] = new List<FlattenedProperty>();
            }
            
            groups[groupName].Add(property);
        }
        
        return groups;
    }
    
    /// <summary>
    /// Get the group name to which the attribute belongs
    /// </summary>
    private string GetOwnerGroupName(string propertyPath)
    {
        if (!propertyPath.Contains('.')) 
            return "Direct";
            
        var parts = propertyPath.Split('.');
        return parts[0]; // 返回第一部分作为分组名
    }
    
    /// <summary>
    /// Build property declaration
    /// </summary>
    private void BuildPropertyDeclaration(StringBuilder sb, FlattenedProperty property)
    {
        // XML documentation comments
        if (!string.IsNullOrWhiteSpace(property.XmlDocumentation))
        {
            sb.AppendLine("    /// <summary>");
            // Handle multi-line comments, ensuring each line has ///
            var lines = property.XmlDocumentation!.Split(new[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in lines)
            {
                sb.AppendLine($"    /// {line.Trim()}");
            }
            sb.AppendLine("    /// </summary>");
        }

        // Use concise type names
        var conciseType = GetConciseTypeString(property.OriginalPropertySymbol.Type);
        
        // Make sure the type is nullable
        if (!conciseType.EndsWith("?") && !IsReferenceType(property.OriginalPropertySymbol.Type))
        {
            conciseType += "?";
        }
        
        // Property definition
        sb.AppendLine($"    public {conciseType} {property.Name} {{ get; set; }}");
        sb.AppendLine();
    }
    
    /// <summary>
    /// Check if it is a reference type
    /// </summary>
    private bool IsReferenceType(ITypeSymbol type)
    {
        return type.IsReferenceType || (type is INamedTypeSymbol namedType && 
                                       namedType.IsGenericType && 
                                       namedType.OriginalDefinition.ToDisplayString().StartsWith("System.Collections.Generic.List<"));
    }

    /// <summary>
    /// Build the GetChanges method and the GenedGetChanges method
    /// </summary>
    private void BuildGetChangesMethod(StringBuilder sb, string entityName, FlattenedPropertyResult flattenedResult)
    {
        // Generate virtual GetChanges method
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Get the current change information.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"entity\">When provided, includes the original entity values related to each change.</param>");
        sb.AppendLine("    /// <returns>The property-change list.</returns>");
        sb.AppendLine($"    public virtual IEnumerable<PropertyChange> GetChanges({entityName}? entity = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        return GenedGetChanges(entity);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate the GenedGetChanges method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Generated GetChanges logic.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"entity\">When provided, includes the original entity values related to each change.</param>");
        sb.AppendLine("    /// <returns>The property-change list.</returns>");
        sb.AppendLine($"    protected IEnumerable<PropertyChange> GenedGetChanges({entityName}? entity = null)");
        sb.AppendLine("    {");

        // Handle direct properties (properties flattened from Owned type)
        var directProperties = flattenedResult.Properties.Where(p => !p.IsOptionalNavigation).ToList();
        foreach (var property in directProperties)
        {
            BuildGetChangesPropertyYield(sb, property);
        }

        // Handling navigation property groups
        foreach (var navGroup in flattenedResult.NavigationGroups)
        {
            foreach (var property in navGroup.Properties)
            {
                BuildGetChangesPropertyYield(sb, property);
            }
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Construct property yield return code in GetChanges method
    /// </summary>
    private void BuildGetChangesPropertyYield(StringBuilder sb, FlattenedProperty property)
    {
        sb.AppendLine($"        if ({property.Name} != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            yield return new PropertyChange");
        sb.AppendLine("            {");
        
        // Prefer the change-item property Title. Otherwise use the property name.
        var displayName = GetPropertyDisplayName(property);
        sb.AppendLine($"                DisplayName = \"{displayName}\",");
        sb.AppendLine($"                PropertyName = nameof({property.Name}),");
        sb.AppendLine($"                NewValue = {property.Name},");
        
        // Handling safe access to nullable navigation properties
        var safePropertyPath = MakeSafePropertyPath(property.PropertyPath);
        sb.AppendLine($"                OldValue = entity?.{safePropertyPath}");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Convert property paths to safe nullable access paths
    /// </summary>
    private string MakeSafePropertyPath(string propertyPath)
    {
        // Convert "DepInfo.COBT" to "DepInfo?.COBT"
        var parts = propertyPath.Split('.');
        if (parts.Length > 1)
        {
            return string.Join("?.", parts);
        }
        return propertyPath;
    }

    /// <summary>
    /// Convert property paths to non-null access paths (for assignment statements)
    /// </summary>
    private string MakeNonNullPropertyPath(string propertyPath)
    {
        // Convert "DepInfo.COBT" to "DepInfo!.COBT"
        var parts = propertyPath.Split('.');
        if (parts.Length > 1)
        {
            // The first part is the navigation attribute, which needs to be added!
            return parts[0] + "!." + string.Join(".", parts.Skip(1));
        }
        return propertyPath;
    }

    /// <summary>
    /// Get the property display name.
    /// </summary>
    private string GetPropertyDisplayName(FlattenedProperty property)
    {
        // Check the change-item property attribute's Title setting.
        var alterItemAttr = property.OriginalPropertySymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == "ChangeItemPropertyAttribute");
        
        if (alterItemAttr != null)
        {
            // Find the Title property
            var titleNamedArg = alterItemAttr.NamedArguments
                .FirstOrDefault(arg => arg.Key == "Title");
            
            if (!titleNamedArg.Equals(default(KeyValuePair<string, TypedConstant>)) && 
                titleNamedArg.Value.Value is string titleValue && 
                !string.IsNullOrEmpty(titleValue))
            {
                return titleValue;
            }
        }
        
        // Return attribute name by default
        return property.Name;
    }
}
