<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <GenerateStaticWebAssetsManifest>true</GenerateStaticWebAssetsManifest>
    <NoWarn>$(NoWarn);CS1998</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageDescription>Framework UI dashboards and admin panels for Monica framework, providing monitoring and management interfaces for framework components.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\Monica.DependencyInjection\Monica.DependencyInjection.csproj" />
    <ProjectReference Include="..\Monica.Framework\Monica.Framework.csproj" />
    <ProjectReference Include="..\Monica.JobScheduler.UI\Monica.JobScheduler.UI.csproj" />
    <ProjectReference Include="..\Monica.StateStore.UI\Monica.StateStore.UI.csproj" />
    <ProjectReference Include="..\Monica.UI\Monica.UI.csproj" />
    <ProjectReference Include="..\Monica.Logging\Monica.Logging.csproj" />
    <ProjectReference Include="..\Monica.ProjectUnits\Monica.ProjectUnits.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\**\*.json" />
  </ItemGroup>
</Project>
