<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Test.Monica</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Monica.Core\Monica.Core.csproj" />
    <ProjectReference Include="..\..\Monica.UI\Monica.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>
</Project>
