using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Monica.Generators.AutoController.Generators;
using Monica.Generators.AutoController.Models;

namespace Monica.Generators.AutoController;

/// <summary>
/// Source generator that creates RPC client interfaces and implementations from metadata files.
/// This generator reads .rpc-metadata.json files (generated by API projects) and generates
/// corresponding client code for RPC communication.
/// </summary>
[Generator]
public class RpcClientSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Uncomment to attach debugger during development
        // Debugger.Launch();

        // Extract client configuration from assembly-level attributes
        var clientConfigProvider = context.CompilationProvider
            .Select((compilation, token) => ExtractClientConfiguration(compilation));

        // Create a provider for RPC metadata files from AdditionalFiles
        var metadataFilesProvider = context.AdditionalTextsProvider
            .Where(static file =>
            {
                // Filter only .rpc-metadata.json files
                return file.Path.EndsWith(".rpc-metadata.json");
            })
            .Select((file, token) =>
            {
                var content = file.GetText(token)?.ToString();
                if (string.IsNullOrEmpty(content))
                    return (file.Path, Metadata: (RpcMetadata?)null, Error: "Empty file");

                try
                {
                    var metadata = ParseMetadataJson(content!);
                    return (file.Path, Metadata: metadata, Error: (string?)null);
                }
                catch (Exception ex)
                {
                    return (file.Path, Metadata: (RpcMetadata?)null, Error: ex.Message);
                }
            })
            .Collect();

        // Combine configuration with metadata files
        var combinedProvider = clientConfigProvider.Combine(metadataFilesProvider);

        // Register source output
        context.RegisterSourceOutput(combinedProvider, (spc, data) =>
        {
            var (configInfo, metadataFiles) = data;

            // Report configuration error if any
            if (configInfo.ErrorMessage != null)
            {
                ReportDiagnostic(spc, DiagnosticSeverity.Error, "RPC_CLIENT_001",
                    "Configuration Error", configInfo.ErrorMessage, Location.None);
                return;
            }

            // Skip if no client config attribute found
            if (!configInfo.HasClientConfig)
            {
                ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_002",
                    "No Client Config",
                    "RpcClientConfigAttribute not found. Skipping RPC client generation.",
                    Location.None);
                return;
            }

            // Log configuration
            ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_003",
                "Client Config Found",
                $"Found RpcClientConfigAttribute. AddHttp={configInfo.AddHttp}, AddLocal={configInfo.AddLocal}, AddGrpc={configInfo.AddGrpc}, HttpImplType={configInfo.HttpImplType ?? "default"}, LocalImplType={configInfo.LocalImplType ?? "default"}",
                Location.None);

            // Process metadata files
            var validMetadata = new List<RpcMetadata>();
            var fileCount = metadataFiles.Length;

            ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_004",
                "Metadata Files Found",
                $"Found {fileCount} RPC metadata file(s)",
                Location.None);

            foreach (var (path, metadata, error) in metadataFiles)
            {
                if (error != null)
                {
                    ReportDiagnostic(spc, DiagnosticSeverity.Warning, "RPC_CLIENT_005",
                        "Metadata Parse Error",
                        $"Failed to parse {path}: {error}",
                        Location.None);
                    continue;
                }

                if (metadata != null)
                {
                    validMetadata.Add(metadata);
                    ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_006",
                        "Metadata Loaded",
                        $"Loaded metadata for {metadata.DomainName ?? metadata.AssemblyName} with {metadata.Handlers.Count} handler(s)",
                        Location.None);
                }
            }

            // Generate clients if we have valid metadata
            if (validMetadata.Count == 0)
            {
                ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_007",
                    "No Valid Metadata",
                    "No valid RPC metadata found. API projects may need to be built first to generate metadata files.",
                    Location.None);
                return;
            }

            if (!configInfo.AddHttp && !configInfo.AddLocal && !configInfo.AddGrpc)
            {
                ReportDiagnostic(spc, DiagnosticSeverity.Info, "RPC_CLIENT_011",
                    "No Transport Enabled",
                    "RPC client generation is enabled, but no transport implementation was requested.",
                    Location.None);
                return;
            }

            GenerateClients(spc, validMetadata, configInfo);

            if (configInfo.AddGrpc)
            {
                // TODO: Implement gRPC client generation
                ReportDiagnostic(spc, DiagnosticSeverity.Warning, "RPC_CLIENT_008",
                    "gRPC Not Implemented",
                    "gRPC client generation is not yet implemented",
                    Location.None);
            }
        });
    }

    /// <summary>
    /// Generates RPC client interfaces and implementations for all domains.
    /// </summary>
    private static void GenerateClients(
        SourceProductionContext context,
        List<RpcMetadata> metadataList,
        RpcClientGenerationConfiguration configInfo)
    {
        foreach (var metadata in metadataList)
        {
            try
            {
                var generatedFiles = RpcClientCodeGenerator.GenerateClientForDomain(
                    metadata,
                    configInfo.AddHttp,
                    configInfo.HttpImplType,
                    configInfo.AddLocal,
                    configInfo.LocalImplType);

                var domainName = metadata.DomainName ?? metadata.AssemblyName.Replace(".API", "").Replace("Service", "");

                // Add all generated files
                foreach (var (fileName, content) in generatedFiles)
                {
                    context.AddSource(fileName, content);
                }

                ReportDiagnostic(context, DiagnosticSeverity.Info, "RPC_CLIENT_009",
                    "Client Generated",
                    $"Generated {generatedFiles.Count} RPC client file(s) for {domainName} domain",
                    Location.None);
            }
            catch (Exception ex)
            {
                ReportDiagnostic(context, DiagnosticSeverity.Error, "RPC_CLIENT_010",
                    "Generation Error",
                    $"Failed to generate client for {metadata.DomainName}: {ex.Message}",
                    Location.None);
            }
        }
    }

    /// <summary>
    /// Parses RPC metadata from JSON string.
    /// Uses simple regex-based parsing to avoid dependencies.
    /// </summary>
    private static RpcMetadata ParseMetadataJson(string json)
    {
        var metadata = new RpcMetadata();
        
        // Parse assembly name
        var assemblyNameMatch = Regex.Match(json, @"""AssemblyName""\s*:\s*""([^""]*)""");
        if (assemblyNameMatch.Success)
            metadata.AssemblyName = assemblyNameMatch.Groups[1].Value;

        // Parse domain name
        var domainNameMatch = Regex.Match(json, @"""DomainName""\s*:\s*""([^""]*)""");
        if (domainNameMatch.Success)
            metadata.DomainName = domainNameMatch.Groups[1].Value;

        // Parse route prefix
        var routePrefixMatch = Regex.Match(json, @"""RoutePrefix""\s*:\s*""([^""]*)""");
        if (routePrefixMatch.Success)
            metadata.RoutePrefix = routePrefixMatch.Groups[1].Value;

        // Parse related namespaces array
        var namespacesMatch = Regex.Match(json, @"""RelatedNamespaces""\s*:\s*\[(.*?)\]", RegexOptions.Singleline);
        if (namespacesMatch.Success)
        {
            var namespacesJson = namespacesMatch.Groups[1].Value;
            // Extract each namespace string
            var namespaceMatches = Regex.Matches(namespacesJson, @"""([^""]*)""");
            foreach (Match nsMatch in namespaceMatches)
            {
                var ns = nsMatch.Groups[1].Value;
                if (!string.IsNullOrEmpty(ns) && !metadata.RelatedNamespaces.Contains(ns))
                {
                    metadata.RelatedNamespaces.Add(ns);
                }
            }

            metadata.RelatedNamespaces.Sort(StringComparer.Ordinal);
        }

        // Parse handlers array
        var handlersMatch = Regex.Match(json, @"""Handlers""\s*:\s*\[(.*)\]", RegexOptions.Singleline);
        if (handlersMatch.Success)
        {
            var handlersJson = handlersMatch.Groups[1].Value;
            // Extract handler objects using balanced brace matching
            var handlers = ExtractJsonObjects(handlersJson);

            foreach (var handlerJson in handlers)
            {
                var handler = ParseHandlerMetadata(handlerJson);
                if (handler != null)
                    metadata.Handlers.Add(handler);
            }
        }

        return metadata;
    }
    
    /// <summary>
    /// Extracts JSON objects from a JSON array content using balanced brace matching.
    /// Handles nested braces in string values correctly.
    /// </summary>
    private static List<string> ExtractJsonObjects(string jsonArrayContent)
    {
        var result = new List<string>();
        var current = new StringBuilder();
        int braceDepth = 0;
        bool inString = false;
        bool escaped = false;

        foreach (char c in jsonArrayContent)
        {
            if (escaped)
            {
                current.Append(c);
                escaped = false;
                continue;
            }

            if (c == '\\' && inString)
            {
                current.Append(c);
                escaped = true;
                continue;
            }

            if (c == '"')
            {
                inString = !inString;
                current.Append(c);
                continue;
            }

            if (inString)
            {
                current.Append(c);
                continue;
            }

            if (c == '{')
            {
                braceDepth++;
                current.Append(c);
            }
            else if (c == '}')
            {
                current.Append(c);
                braceDepth--;

                if (braceDepth == 0 && current.Length > 0)
                {
                    // Complete object found
                    result.Add(current.ToString());
                    current.Clear();
                }
            }
            else
            {
                current.Append(c);
            }
        }

        return result;
    }

    /// <summary>
    /// Parses a single handler metadata object from JSON.
    /// </summary>
    private static HandlerMetadata? ParseHandlerMetadata(string json)
    {
        try
        {
            var handler = new HandlerMetadata
            {
                RequestType = ExtractJsonString(json, "RequestType") ?? "",
                ResponseType = ExtractJsonString(json, "ResponseType") ?? "",
                HttpMethod = ExtractJsonString(json, "HttpMethod") ?? "",
                Route = ExtractJsonString(json, "Route") ?? "",
                ClientMethodName = ExtractJsonString(json, "ClientMethodName") ?? "",
                HandlerType = ExtractJsonString(json, "HandlerType") ?? "",
                Summary = ExtractJsonString(json, "Summary") ?? ""
            };

            return handler;
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Extracts a string value from a JSON property.
    /// Handles escaped characters including escaped quotes (\").
    /// </summary>
    private static string? ExtractJsonString(string json, string propertyName)
    {
        // Regex pattern that handles escaped characters:
        // - [^"\\]* matches any character except " and \
        // - (?:\\.[^"\\]*)* matches zero or more occurrences of: \ followed by any char, then any non-" non-\ chars
        var match = Regex.Match(json, $@"""{propertyName}""\s*:\s*""([^""\\]*(?:\\.[^""\\]*)*)""");
        if (!match.Success)
            return null;

        // Unescape the matched string (replace \" with ", \\ with \, etc.)
        var escaped = match.Groups[1].Value;
        return Regex.Replace(escaped, @"\\(.)", "$1");
    }

    /// <summary>
    /// Extracts the client configuration from assembly-level attributes.
    /// </summary>
    private static RpcClientGenerationConfiguration
        ExtractClientConfiguration(Compilation compilation)
    {
        try
        {
            var assemblyAttributes = compilation.Assembly.GetAttributes();
            AttributeData? clientConfigAttribute = null;

            // Find the RpcClientConfigAttribute
            foreach (var attribute in assemblyAttributes)
            {
                if (attribute.AttributeClass?.Name == "RpcClientConfigAttribute")
                {
                    clientConfigAttribute = attribute;
                    break;
                }
            }

            if (clientConfigAttribute == null)
            {
                return new RpcClientGenerationConfiguration();
            }

            // Extract configuration values
            bool addGrpc = false;
            bool addHttp = true;
            bool addLocal = false;
            string? httpImplType = null;
            string? localImplType = null;

            foreach (var namedArgument in clientConfigAttribute.NamedArguments)
            {
                switch (namedArgument.Key)
                {
                    case "AddGrpcImplementations":
                        if (namedArgument.Value.Value is bool grpcValue)
                            addGrpc = grpcValue;
                        break;
                    case "AddHttpImplementations":
                        if (namedArgument.Value.Value is bool httpValue)
                            addHttp = httpValue;
                        break;
                    case "AddLocalImplementations":
                        if (namedArgument.Value.Value is bool localValue)
                            addLocal = localValue;
                        break;
                    case "HttpImplementationType":
                        if (namedArgument.Value.Value is INamedTypeSymbol typeSymbol)
                            httpImplType = typeSymbol.ToDisplayString();
                        break;
                    case "LocalImplementationType":
                        if (namedArgument.Value.Value is INamedTypeSymbol localTypeSymbol)
                            localImplType = localTypeSymbol.ToDisplayString();
                        break;
                }
            }

            if (addHttp)
            {
                httpImplType ??= ResolveDefaultHttpImplementationType(compilation);
            }

            if (addLocal)
            {
                localImplType ??= ResolveDefaultLocalImplementationType(compilation);
            }

            return new RpcClientGenerationConfiguration(
                hasClientConfig: true,
                httpImplType: httpImplType,
                localImplType: localImplType,
                addGrpc: addGrpc,
                addHttp: addHttp,
                addLocal: addLocal,
                errorMessage: null);
        }
        catch (Exception ex)
        {
            return new RpcClientGenerationConfiguration(
                errorMessage: $"Failed to extract client configuration: {ex.Message}");
        }
    }

    private static string ResolveDefaultHttpImplementationType(Compilation compilation)
    {
        var httpRpcApiSymbol = compilation.GetTypeByMetadataName("Monica.WebApi.RpcClient.Abstractions.HttpRpcApi");
        if (httpRpcApiSymbol == null)
        {
            throw new InvalidOperationException(
                "Unable to resolve Monica.WebApi.RpcClient.Abstractions.HttpRpcApi from the current compilation.");
        }

        return httpRpcApiSymbol.ToDisplayString();
    }

    private static string ResolveDefaultLocalImplementationType(Compilation compilation)
    {
        var localRpcApiSymbol = compilation.GetTypeByMetadataName("Monica.WebApi.RpcClient.Abstractions.LocalRpcApi");
        if (localRpcApiSymbol == null)
        {
            throw new InvalidOperationException(
                "Unable to resolve Monica.WebApi.RpcClient.Abstractions.LocalRpcApi from the current compilation.");
        }

        return localRpcApiSymbol.ToDisplayString();
    }

    /// <summary>
    /// Helper method to report diagnostics with consistent formatting.
    /// </summary>
    private static void ReportDiagnostic(
        SourceProductionContext context,
        DiagnosticSeverity severity,
        string id,
        string title,
        string message,
        Location location)
    {
        var descriptor = new DiagnosticDescriptor(
            id: id,
            title: title,
            messageFormat: message,
            category: "RpcClientGenerator",
            defaultSeverity: severity,
            isEnabledByDefault: true);

        context.ReportDiagnostic(Diagnostic.Create(descriptor, location));
    }

    private readonly struct RpcClientGenerationConfiguration
    {
        public RpcClientGenerationConfiguration(
            bool hasClientConfig = false,
            string? httpImplType = null,
            string? localImplType = null,
            bool addGrpc = false,
            bool addHttp = false,
            bool addLocal = false,
            string? errorMessage = null)
        {
            HasClientConfig = hasClientConfig;
            HttpImplType = httpImplType;
            LocalImplType = localImplType;
            AddGrpc = addGrpc;
            AddHttp = addHttp;
            AddLocal = addLocal;
            ErrorMessage = errorMessage;
        }

        public bool HasClientConfig { get; }

        public string? HttpImplType { get; }

        public string? LocalImplType { get; }

        public bool AddGrpc { get; }

        public bool AddHttp { get; }

        public bool AddLocal { get; }

        public string? ErrorMessage { get; }
    }
}
