<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.xml" />

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="10.7.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />     
    <PackageReference Include="Unchase.Swashbuckle.AspNetCore.Extensions" Version="2.7.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.Authority\MoLibrary.Authority.csproj" />
    <ProjectReference Include="..\MoLibrary.AutoModel\MoLibrary.AutoModel.csproj" />
    <ProjectReference Include="..\MoLibrary.Core\MoLibrary.Core.csproj" />
    <ProjectReference Include="..\MoLibrary.DependencyInjection\MoLibrary.DependencyInjection.csproj" />
    <ProjectReference Include="..\MoLibrary.Repository\MoLibrary.Repository.csproj" />
  </ItemGroup>
</Project>
