<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\common.xml"/>

  <PropertyGroup>
    <GenerateStaticWebAssetsManifest>true</GenerateStaticWebAssetsManifest>
    <NoWarn>$(NoWarn);CS1998</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoLibrary.AI\MoLibrary.AI.csproj" />
    <ProjectReference Include="..\MoLibrary.UI\MoLibrary.UI.csproj" />
  </ItemGroup>

</Project>
