<Project Sdk="Microsoft.NET.Sdk">
<Import Project="..\..\common.xml"/>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.DistributedLock" Version="1.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="4.0.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NSubstitute" Version="5.1.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Monica.Dapr\Monica.Dapr.csproj" />
    <ProjectReference Include="..\..\Monica.Locker\Monica.Locker.csproj" />
  </ItemGroup>

</Project> 