<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.xml"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Monica.DataChannel\Monica.DataChannel.csproj" />
    <ProjectReference Include="..\..\Monica.Framework\Monica.Framework.csproj" />
  </ItemGroup>

</Project>